from __future__ import annotations

"""Manuscript writing support tools.

These tools do mechanical organization for T8. They do not write scientific
claims. The Writer LLM remains responsible for argumentation, section prose,
claim selection, and venue-aware framing.
"""

import csv
import json
import re
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field

from .base import Tool, ToolResult
from .workspace_policy import ToolAccessDenied, WorkspaceAccessPolicy


CORE_SECTIONS = [
    "abstract",
    "introduction",
    "related_work",
    "methodology",
    "experiments",
    "analysis",
    "limitations",
    "conclusion",
]

SECTION_WRITING_SEQUENCE = [
    "methodology",
    "experiments",
    "related_work",
    "analysis",
    "introduction",
    "limitations",
    "conclusion",
    "abstract",
]

SECTION_TITLES = {
    "abstract": "Abstract",
    "introduction": "Introduction",
    "related_work": "Related Work",
    "methodology": "Method",
    "experiments": "Experiments",
    "analysis": "Analysis",
    "limitations": "Limitations",
    "conclusion": "Conclusion",
}

SECTION_ALIASES = {
    "intro": "introduction",
    "introduction": "introduction",
    "related": "related_work",
    "related-work": "related_work",
    "related_work": "related_work",
    "literature_review": "related_work",
    "literature-review": "related_work",
    "method": "methodology",
    "methods": "methodology",
    "methodology": "methodology",
    "approach": "methodology",
    "experiment": "experiments",
    "experiments": "experiments",
    "evaluation": "experiments",
    "results": "experiments",
    "discussion": "analysis",
    "analysis": "analysis",
    "limitation": "limitations",
    "limitations": "limitations",
    "conclusion": "conclusion",
    "abstract": "abstract",
}


class BuildManuscriptResourceIndexParams(BaseModel):
    output_path: str = Field(
        default="drafts/manuscript_resource_index.json",
        description="Relative path for the manuscript resource index JSON.",
    )
    include_previews: bool = Field(
        default=True,
        description="Whether to include short text previews for major source artifacts.",
    )


class PlanManuscriptSectionsParams(BaseModel):
    resource_index_path: str = Field(
        default="drafts/manuscript_resource_index.json",
        description="Resource index generated by build_manuscript_resource_index.",
    )
    output_path: str = Field(
        default="drafts/section_plan.json",
        description="Relative path for the section plan JSON.",
    )
    target_venue: str = Field(default="", description="Target venue or journal/conference name.")
    paper_type: Literal["empirical", "systems", "theory", "survey", "auto"] = Field(
        default="auto",
        description="Paper type hint; auto uses project/results artifacts.",
    )


class PlanManuscriptEvidenceParams(BaseModel):
    resource_index_path: str = Field(
        default="drafts/manuscript_resource_index.json",
        description="Resource index generated by build_manuscript_resource_index.",
    )
    evidence_output_path: str = Field(
        default="drafts/evidence_plan.json",
        description="Relative path for the evidence and claim-slot plan.",
    )
    figure_output_path: str = Field(
        default="drafts/figure_table_plan.json",
        description="Relative path for the figure/table plan.",
    )
    target_venue: str = Field(default="", description="Target venue or journal/conference name.")


class InitializeManuscriptStateParams(BaseModel):
    outline_path: str = Field(default="drafts/outline.md", description="Global outline path.")
    resource_index_path: str = Field(
        default="drafts/manuscript_resource_index.json",
        description="Resource index generated by build_manuscript_resource_index.",
    )
    section_plan_path: str = Field(
        default="drafts/section_plan.json",
        description="Section plan generated by plan_manuscript_sections.",
    )
    evidence_plan_path: str = Field(
        default="drafts/evidence_plan.json",
        description="Evidence plan generated by plan_manuscript_evidence.",
    )
    figure_table_plan_path: str = Field(
        default="drafts/figure_table_plan.json",
        description="Figure/table plan generated by plan_manuscript_evidence.",
    )
    state_output_path: str = Field(
        default="drafts/paper_state.json",
        description="Relative path for the shared manuscript state JSON.",
    )
    section_outline_dir: str = Field(
        default="drafts/section_outlines",
        description="Directory for per-section outline markdown files.",
    )
    target_venue: str = Field(default="", description="Target venue or journal/conference name.")


class UpdateManuscriptSectionStateParams(BaseModel):
    section_id: str = Field(description="Section id, e.g. methodology, experiments, introduction.")
    state_path: str = Field(default="drafts/paper_state.json", description="Shared manuscript state JSON.")
    section_path: str = Field(
        default="",
        description="Relative section file path. Defaults to drafts/sections/{section_id}.tex.",
    )
    status: Literal["written", "revised"] = Field(
        default="written",
        description="Section completion status to record in paper_state.json.",
    )


class AssembleManuscriptParams(BaseModel):
    section_dir: str = Field(default="drafts/sections", description="Directory containing section drafts.")
    output_path: str = Field(default="drafts/paper.tex", description="LaTeX output path.")
    outline_path: str = Field(default="drafts/outline.md", description="Outline path.")
    title: str = Field(default="", description="Optional paper title override.")
    target_venue: str = Field(default="", description="Target venue name used in comments only.")


class AuditManuscriptClaimsParams(BaseModel):
    paper_path: str = Field(default="drafts/paper.tex", description="Paper draft path.")
    output_path: str = Field(default="drafts/manuscript_audit.md", description="Audit report path.")
    resource_index_path: str = Field(
        default="drafts/manuscript_resource_index.json",
        description="Resource index path.",
    )


class BuildManuscriptRevisionPatchesParams(BaseModel):
    round_num: int = Field(default=1, description="Review round number.")
    review_report_path: str = Field(
        default="",
        description="Review report path. Defaults to drafts/review_rounds/round_{round_num}.md.",
    )
    section_review_dir: str = Field(
        default="",
        description="Section review directory. Defaults to drafts/review_rounds/round_{round_num}_sections.",
    )
    output_path: str = Field(
        default="",
        description="Patch list output path. Defaults to drafts/patches/round_{round_num}_patches.json.",
    )
    include_low: bool = Field(default=True, description="Include Low-severity issues in the patch list.")


class BuildManuscriptResourceIndexTool(Tool):
    name = "build_manuscript_resource_index"
    description = (
        "Build a mechanical index of manuscript-writing resources: project, literature synthesis, "
        "paper notes, bibliography, hypotheses, novelty audit, experiment results, ablations, "
        "figures, tables, code artifacts, and logs. It only records provenance and previews."
    )
    parameters_schema = BuildManuscriptResourceIndexParams
    timeout_seconds = 30.0

    def __init__(self, policy: WorkspaceAccessPolicy):
        self.policy = policy

    async def execute(self, **kwargs: Any) -> ToolResult:
        params = BuildManuscriptResourceIndexParams(**kwargs)
        try:
            output_path = self.policy.resolve_write(params.output_path)
            ws = self.policy.workspace_dir
            index = build_resource_index(ws, include_previews=params.include_previews)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(json.dumps(index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        except ToolAccessDenied as exc:
            return ToolResult(ok=False, content=str(exc), error="access_denied")
        except Exception as exc:
            return ToolResult(ok=False, content=f"resource index failed: {exc}", error="index_failed")

        return ToolResult(
            ok=True,
            content=(
                f"Built manuscript resource index at {params.output_path}: "
                f"{len(index.get('artifacts', []))} artifacts, "
                f"{len(index.get('figures', []))} figures, "
                f"{len(index.get('tables', []))} tables."
            ),
            data=index,
        )


class PlanManuscriptSectionsTool(Tool):
    name = "plan_manuscript_sections"
    description = (
        "Create a mechanical section writing plan from the resource index. The plan maps each "
        "standard paper section to required inputs, evidence files, expected outputs, and LLM review notes."
    )
    parameters_schema = PlanManuscriptSectionsParams
    timeout_seconds = 30.0

    def __init__(self, policy: WorkspaceAccessPolicy):
        self.policy = policy

    async def execute(self, **kwargs: Any) -> ToolResult:
        params = PlanManuscriptSectionsParams(**kwargs)
        try:
            index_candidate = self.policy.workspace_dir / params.resource_index_path
            if index_candidate.exists():
                index_path = self.policy.resolve_read(params.resource_index_path)
                index = json.loads(index_path.read_text(encoding="utf-8"))
            else:
                index = build_resource_index(self.policy.workspace_dir, include_previews=False)
            plan = build_section_plan(index, target_venue=params.target_venue, paper_type=params.paper_type)
            output_path = self.policy.resolve_write(params.output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(json.dumps(plan, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        except ToolAccessDenied as exc:
            return ToolResult(ok=False, content=str(exc), error="access_denied")
        except FileNotFoundError as exc:
            return ToolResult(ok=False, content=f"missing resource index: {exc}", error="missing_index")
        except Exception as exc:
            return ToolResult(ok=False, content=f"section planning failed: {exc}", error="planning_failed")

        return ToolResult(
            ok=True,
            content=f"Wrote section plan to {params.output_path} with {len(plan['sections'])} sections.",
            data=plan,
        )


class PlanManuscriptEvidenceTool(Tool):
    name = "plan_manuscript_evidence"
    description = (
        "Create mechanical evidence, claim-slot, figure, and table plans from the manuscript "
        "resource index. It does not decide scientific claims; it lists provenance and slots the "
        "Writer LLM must fill or mark unsupported."
    )
    parameters_schema = PlanManuscriptEvidenceParams
    timeout_seconds = 30.0

    def __init__(self, policy: WorkspaceAccessPolicy):
        self.policy = policy

    async def execute(self, **kwargs: Any) -> ToolResult:
        params = PlanManuscriptEvidenceParams(**kwargs)
        try:
            index_candidate = self.policy.workspace_dir / params.resource_index_path
            if index_candidate.exists():
                index_path = self.policy.resolve_read(params.resource_index_path)
                index = json.loads(index_path.read_text(encoding="utf-8"))
            else:
                index = build_resource_index(self.policy.workspace_dir, include_previews=False)
            evidence_plan, figure_plan = build_evidence_and_figure_plans(
                index,
                target_venue=params.target_venue,
            )
            evidence_path = self.policy.resolve_write(params.evidence_output_path)
            figure_path = self.policy.resolve_write(params.figure_output_path)
            evidence_path.parent.mkdir(parents=True, exist_ok=True)
            figure_path.parent.mkdir(parents=True, exist_ok=True)
            evidence_path.write_text(
                json.dumps(evidence_plan, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            figure_path.write_text(
                json.dumps(figure_plan, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
        except ToolAccessDenied as exc:
            return ToolResult(ok=False, content=str(exc), error="access_denied")
        except Exception as exc:
            return ToolResult(ok=False, content=f"evidence planning failed: {exc}", error="planning_failed")

        return ToolResult(
            ok=True,
            content=(
                f"Wrote evidence plan to {params.evidence_output_path} and figure/table plan "
                f"to {params.figure_output_path}."
            ),
            data={"evidence_plan": evidence_plan, "figure_table_plan": figure_plan},
        )


class InitializeManuscriptStateTool(Tool):
    name = "initialize_manuscript_state"
    description = (
        "Initialize drafts/paper_state.json and drafts/section_outlines/*.md for true "
        "section-by-section manuscript writing. It creates mechanical shared-fact candidates "
        "and per-section writing briefs; the Writer LLM must refine claims and prose."
    )
    parameters_schema = InitializeManuscriptStateParams
    timeout_seconds = 30.0

    def __init__(self, policy: WorkspaceAccessPolicy):
        self.policy = policy

    async def execute(self, **kwargs: Any) -> ToolResult:
        params = InitializeManuscriptStateParams(**kwargs)
        try:
            ws = self.policy.workspace_dir
            outline = _read_optional_text(self.policy, params.outline_path)
            index = _read_optional_json(self.policy, params.resource_index_path)
            section_plan = _read_optional_json(self.policy, params.section_plan_path)
            evidence_plan = _read_optional_json(self.policy, params.evidence_plan_path)
            figure_plan = _read_optional_json(self.policy, params.figure_table_plan_path)
            state = build_paper_state(
                outline_path=params.outline_path,
                outline_text=outline,
                index=index,
                section_plan=section_plan,
                evidence_plan=evidence_plan,
                figure_plan=figure_plan,
                section_outline_dir=params.section_outline_dir,
                target_venue=params.target_venue,
            )
            state_path = self.policy.resolve_write(params.state_output_path)
            outline_dir = self.policy.resolve_write(
                f"{params.section_outline_dir.rstrip('/')}/_manifest.txt"
            ).parent
            state_path.parent.mkdir(parents=True, exist_ok=True)
            outline_dir.mkdir(parents=True, exist_ok=True)
            state_path.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
            outlines = build_section_outlines(
                state,
                section_plan=section_plan,
                evidence_plan=evidence_plan,
                figure_plan=figure_plan,
                outline_text=outline,
            )
            for section_id, text in outlines.items():
                path = self.policy.resolve_write(
                    f"{params.section_outline_dir.rstrip('/')}/{section_id}.md"
                )
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")
        except ToolAccessDenied as exc:
            return ToolResult(ok=False, content=str(exc), error="access_denied")
        except Exception as exc:
            return ToolResult(ok=False, content=f"manuscript state initialization failed: {exc}", error="state_init_failed")

        return ToolResult(
            ok=True,
            content=(
                f"Initialized manuscript state at {params.state_output_path} and "
                f"{len(outlines)} section outlines under {params.section_outline_dir}."
            ),
            data={
                "state_path": params.state_output_path,
                "section_outline_dir": params.section_outline_dir,
                "sections": state.get("section_order", []),
            },
        )


class UpdateManuscriptSectionStateTool(Tool):
    name = "update_manuscript_section_state"
    description = (
        "Record that one manuscript section file has been written or revised in paper_state.json. "
        "This is a mechanical status update after the Writer LLM creates the section prose."
    )
    parameters_schema = UpdateManuscriptSectionStateParams
    timeout_seconds = 10.0

    def __init__(self, policy: WorkspaceAccessPolicy):
        self.policy = policy

    async def execute(self, **kwargs: Any) -> ToolResult:
        params = UpdateManuscriptSectionStateParams(**kwargs)
        section_id = normalize_section_id(params.section_id)
        section_rel = params.section_path or f"drafts/sections/{section_id}.tex"
        try:
            state_path = self.policy.resolve_read(params.state_path)
            state = json.loads(state_path.read_text(encoding="utf-8"))
            section_path = self.policy.resolve_read(section_rel)
            text = section_path.read_text(encoding="utf-8")
            if "\\documentclass" in text or "\\begin{document}" in text or "\\end{document}" in text:
                return ToolResult(
                    ok=False,
                    content=f"section file contains whole-document wrapper: {section_rel}",
                    error="section_wrapper_detected",
                )
            sections = state.setdefault("sections", {})
            entry = sections.setdefault(section_id, {})
            entry.update(
                {
                    "status": params.status,
                    "file": section_rel,
                    "chars": len(text.strip()),
                    "last_excerpt": text.strip()[:400],
                }
            )
            state["current_section"] = section_id
            state["last_written_section"] = section_id
            revision_log = state.setdefault("revision_log", [])
            if isinstance(revision_log, list):
                revision_log.append(
                    {
                        "section_id": section_id,
                        "status": params.status,
                        "file": section_rel,
                        "chars": len(text.strip()),
                    }
                )
            write_path = self.policy.resolve_write(params.state_path)
            write_path.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        except ToolAccessDenied as exc:
            return ToolResult(ok=False, content=str(exc), error="access_denied")
        except FileNotFoundError as exc:
            return ToolResult(ok=False, content=f"missing state or section file: {exc}", error="missing_file")
        except Exception as exc:
            return ToolResult(ok=False, content=f"section state update failed: {exc}", error="state_update_failed")

        return ToolResult(
            ok=True,
            content=f"Updated {params.state_path}: {section_id} -> {params.status} ({len(text.strip())} chars).",
            data={"section_id": section_id, "state_path": params.state_path, "section_path": section_rel},
        )


class AssembleManuscriptTool(Tool):
    name = "assemble_manuscript"
    description = (
        "Assemble section drafts from drafts/sections/*.tex or *.md into drafts/paper.tex. "
        "This is mechanical assembly only; it does not generate missing scientific prose."
    )
    parameters_schema = AssembleManuscriptParams
    timeout_seconds = 30.0

    def __init__(self, policy: WorkspaceAccessPolicy):
        self.policy = policy

    async def execute(self, **kwargs: Any) -> ToolResult:
        params = AssembleManuscriptParams(**kwargs)
        try:
            section_dir = self.policy.resolve_read(params.section_dir)
            output_path = self.policy.resolve_write(params.output_path)
            outline_path = self.policy.resolve_read(params.outline_path) if (self.policy.workspace_dir / params.outline_path).exists() else None
            assembled = assemble_sections(
                section_dir,
                title=params.title,
                target_venue=params.target_venue,
                outline_text=outline_path.read_text(encoding="utf-8") if outline_path else "",
            )
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(assembled, encoding="utf-8")
        except ToolAccessDenied as exc:
            return ToolResult(ok=False, content=str(exc), error="access_denied")
        except FileNotFoundError as exc:
            return ToolResult(ok=False, content=f"missing section draft: {exc}", error="missing_sections")
        except Exception as exc:
            return ToolResult(ok=False, content=f"assembly failed: {exc}", error="assembly_failed")

        return ToolResult(
            ok=True,
            content=f"Assembled manuscript to {params.output_path} ({len(assembled)} chars).",
            data={"path": params.output_path, "chars": len(assembled)},
        )


class AuditManuscriptClaimsTool(Tool):
    name = "audit_manuscript_claims"
    description = (
        "Mechanically audit a manuscript for citation keys, numeric values, figure/table references, "
        "and required section presence. It returns issues for LLM/human review, not final scientific judgment."
    )
    parameters_schema = AuditManuscriptClaimsParams
    timeout_seconds = 30.0

    def __init__(self, policy: WorkspaceAccessPolicy):
        self.policy = policy

    async def execute(self, **kwargs: Any) -> ToolResult:
        params = AuditManuscriptClaimsParams(**kwargs)
        try:
            paper_path = self.policy.resolve_read(params.paper_path)
            paper = paper_path.read_text(encoding="utf-8")
            index_candidate = self.policy.workspace_dir / params.resource_index_path
            if index_candidate.exists():
                index_path = self.policy.resolve_read(params.resource_index_path)
                index = json.loads(index_path.read_text(encoding="utf-8"))
            else:
                index = build_resource_index(self.policy.workspace_dir, include_previews=False)
            report = audit_manuscript(paper, index)
            output_path = self.policy.resolve_write(params.output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(report, encoding="utf-8")
        except ToolAccessDenied as exc:
            return ToolResult(ok=False, content=str(exc), error="access_denied")
        except Exception as exc:
            return ToolResult(ok=False, content=f"manuscript audit failed: {exc}", error="audit_failed")

        issue_count = report.count("- [ ]")
        return ToolResult(
            ok=True,
            content=f"Wrote manuscript audit to {params.output_path}; open issues: {issue_count}.",
            data={"path": params.output_path, "open_issues": issue_count},
        )


class BuildManuscriptRevisionPatchesTool(Tool):
    name = "build_manuscript_revision_patches"
    description = (
        "Convert section-aware reviewer reports into a mechanical patch list for T8 revision. "
        "It only locates issues by section/severity/source; the Writer LLM still decides the "
        "scientific wording and how to revise each target section."
    )
    parameters_schema = BuildManuscriptRevisionPatchesParams
    timeout_seconds = 20.0

    def __init__(self, policy: WorkspaceAccessPolicy):
        self.policy = policy

    async def execute(self, **kwargs: Any) -> ToolResult:
        params = BuildManuscriptRevisionPatchesParams(**kwargs)
        round_num = max(1, int(params.round_num or 1))
        review_rel = params.review_report_path or f"drafts/review_rounds/round_{round_num}.md"
        section_dir_rel = params.section_review_dir or f"drafts/review_rounds/round_{round_num}_sections"
        output_rel = params.output_path or f"drafts/patches/round_{round_num}_patches.json"

        try:
            review_text = ""
            review_candidate = self.policy.workspace_dir / review_rel
            if review_candidate.exists():
                review_text = self.policy.resolve_read(review_rel).read_text(
                    encoding="utf-8",
                    errors="replace",
                )

            section_reviews: dict[str, str] = {}
            section_dir = self.policy.workspace_dir / section_dir_rel
            if section_dir.exists() and section_dir.is_dir():
                for section_id in CORE_SECTIONS:
                    path = section_dir / f"{section_id}.md"
                    if path.exists():
                        rel = path.relative_to(self.policy.workspace_dir).as_posix()
                        section_reviews[section_id] = self.policy.resolve_read(rel).read_text(
                            encoding="utf-8",
                            errors="replace",
                        )

            patch_doc = build_revision_patch_list(
                round_num=round_num,
                review_text=review_text,
                section_reviews=section_reviews,
                include_low=params.include_low,
            )
            output_path = self.policy.resolve_write(output_rel)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(
                json.dumps(patch_doc, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
        except ToolAccessDenied as exc:
            return ToolResult(ok=False, content=str(exc), error="access_denied")
        except Exception as exc:
            return ToolResult(ok=False, content=f"revision patch planning failed: {exc}", error="patch_planning_failed")

        return ToolResult(
            ok=True,
            content=f"Wrote revision patch list to {output_rel} with {len(patch_doc['patches'])} patches.",
            data={"path": output_rel, "patch_count": len(patch_doc["patches"]), "patches": patch_doc["patches"]},
        )


def build_resource_index(workspace: Path, *, include_previews: bool = True) -> dict[str, Any]:
    artifacts: list[dict[str, Any]] = []
    for rel in [
        "project.yaml",
        "literature/synthesis.md",
        "literature/synthesis_workbench.json",
        "literature/comparison_table.csv",
        "literature/related_work.bib",
        "ideation/hypotheses.md",
        "ideation/exp_plan.yaml",
        "ideation/idea_scorecard.yaml",
        "ideation/novelty_audit.md",
        "ideation/risks.md",
        "novelty/novelty_report.md",
        "novelty/must_add_baselines.md",
        "experiments/results_summary.json",
        "experiments/ablations.csv",
        "experiments/iteration_log.md",
        "experiments/seed_ensemble_summary.json",
        "experiments/iteration_diversity_check.md",
    ]:
        path = workspace / rel
        if path.exists():
            artifacts.append(_artifact_entry(workspace, path, include_preview=include_previews))

    for pattern in [
        "literature/paper_notes/*.md",
        "literature/paper_notes_abstract/*.md",
        "experiments/runs/**/*",
        "experiments/configs/**/*",
        "experiments/code/**/*",
    ]:
        for path in sorted(workspace.glob(pattern)):
            if path.is_file():
                artifacts.append(_artifact_entry(workspace, path, include_preview=False))

    figures = [_media_entry(workspace, path) for path in _glob_media(workspace, kind="figure")]
    tables = [_media_entry(workspace, path) for path in _glob_media(workspace, kind="table")]
    bib_keys = _extract_bib_keys(workspace / "literature" / "related_work.bib")
    result_metrics = _extract_result_metrics(workspace / "experiments" / "results_summary.json")
    ablation_columns = _csv_columns(workspace / "experiments" / "ablations.csv")

    return {
        "version": "1.0",
        "semantics": "mechanical_resource_index_not_scientific_summary",
        "artifacts": artifacts,
        "figures": figures,
        "tables": tables,
        "bib_keys": bib_keys,
        "result_metrics": result_metrics,
        "ablation_columns": ablation_columns,
        "writing_guidance": {
            "use_llm_for": [
                "claim selection",
                "section argumentation",
                "method explanation",
                "positioning against prior work",
                "limitations and threat interpretation",
            ],
            "use_tools_for": [
                "resource indexing",
                "citation-key extraction",
                "figure/table inventory",
                "section assembly",
                "numeric/citation audit hints",
            ],
        },
    }


def build_section_plan(index: dict[str, Any], *, target_venue: str = "", paper_type: str = "auto") -> dict[str, Any]:
    artifact_paths = {item["path"] for item in index.get("artifacts", [])}
    has_results = "experiments/results_summary.json" in artifact_paths
    has_ablations = "experiments/ablations.csv" in artifact_paths
    has_bib = "literature/related_work.bib" in artifact_paths
    sections = []

    def section(name: str, required: list[str], outputs: list[str], llm_tasks: list[str]) -> None:
        sections.append(
            {
                "id": name,
                "draft_path": f"drafts/sections/{name}.tex",
                "required_inputs": required,
                "available_inputs": [path for path in required if path in artifact_paths],
                "missing_inputs": [path for path in required if path not in artifact_paths],
                "expected_outputs": outputs,
                "llm_tasks": llm_tasks,
                "tool_notes": "Tools provide provenance and inventories only; Writer LLM must write and verify the section.",
            }
        )

    section(
        "abstract",
        ["experiments/results_summary.json", "ideation/hypotheses.md"],
        ["problem/method/result/contribution compressed to venue-appropriate abstract"],
        ["Write last after all main sections exist; do not introduce claims absent from the paper."],
    )
    section(
        "introduction",
        ["project.yaml", "literature/synthesis.md", "ideation/hypotheses.md", "experiments/results_summary.json"],
        ["motivation funnel", "technical gap", "contributions", "result headline"],
        ["Frame the problem from broad setting to precise bottleneck; include honest contribution bullets."],
    )
    section(
        "related_work",
        ["literature/synthesis.md", "literature/related_work.bib", "literature/comparison_table.csv"],
        ["taxonomy", "contrastive positioning", "citation-backed paragraphs"],
        ["Use synthesis families and cite only keys present in bibliography."],
    )
    section(
        "methodology",
        ["ideation/hypotheses.md", "ideation/exp_plan.yaml", "experiments/configs"],
        ["method overview", "algorithm/procedure", "implementation details"],
        ["Explain mechanism and design choices; separate proposed method from experimental protocol."],
    )
    section(
        "experiments",
        ["experiments/results_summary.json", "experiments/ablations.csv", "experiments/seed_ensemble_summary.json"],
        ["setup", "datasets", "baselines", "metrics", "main results", "ablations"],
        ["Every number must come from results artifacts; mark missing stats as TODO rather than inventing."],
    )
    section(
        "analysis",
        ["experiments/iteration_log.md", "experiments/ablations.csv", "ideation/novelty_audit.md"],
        ["mechanism interpretation", "failure cases", "sensitivity analysis"],
        ["Connect ablations back to hypotheses and alternative explanations."],
    )
    section(
        "limitations",
        ["ideation/risks.md", "experiments/iteration_log.md", "ideation/novelty_audit.md"],
        ["threats to validity", "resource limits", "generalization limits"],
        ["Be specific about skipped T5/T6 or direct-full evidence boundaries when applicable."],
    )
    section(
        "conclusion",
        ["drafts/sections/introduction.tex", "drafts/sections/experiments.tex"],
        ["concise contribution recap", "future work"],
        ["Do not overclaim beyond validated results."],
    )

    return {
        "version": "1.0",
        "target_venue": target_venue,
        "paper_type": paper_type,
        "has_results": has_results,
        "has_ablations": has_ablations,
        "has_bibliography": has_bib,
        "recommended_flow": [
            "resource_index",
            "section_plan",
            "outline",
            "section_draft_by_state_machine",
            "assembly",
            "claim_audit",
            "review",
            "revision",
            "submission",
        ],
        "sections": sections,
        "figures_available": index.get("figures", []),
        "tables_available": index.get("tables", []),
    }


def build_evidence_and_figure_plans(
    index: dict[str, Any],
    *,
    target_venue: str = "",
) -> tuple[dict[str, Any], dict[str, Any]]:
    artifact_paths = {item["path"] for item in index.get("artifacts", [])}
    metrics = index.get("result_metrics", [])
    bib_keys = index.get("bib_keys", [])
    figures = index.get("figures", [])
    tables = index.get("tables", [])

    def available(*paths: str) -> list[str]:
        return [path for path in paths if path in artifact_paths]

    claim_slots = [
        {
            "slot_id": "intro_problem_gap",
            "section": "introduction",
            "claim_type": "problem_gap",
            "candidate_evidence": available(
                "literature/synthesis.md",
                "literature/comparison_table.csv",
                "ideation/hypotheses.md",
            ),
            "citation_pool": bib_keys,
            "llm_task": "State the research gap only after checking synthesis and paper notes; do not treat retrieval coverage hints as proven gaps.",
        },
        {
            "slot_id": "intro_contribution_headline",
            "section": "introduction",
            "claim_type": "contribution",
            "candidate_evidence": available(
                "ideation/hypotheses.md",
                "ideation/idea_scorecard.yaml",
                "experiments/results_summary.json",
                "experiments/ablations.csv",
            ),
            "result_metric_candidates": metrics,
            "llm_task": "Write contribution bullets that each map to a hypothesis and at least one result artifact.",
        },
        {
            "slot_id": "related_work_positioning",
            "section": "related_work",
            "claim_type": "prior_work_contrast",
            "candidate_evidence": available(
                "literature/synthesis.md",
                "literature/comparison_table.csv",
                "literature/related_work.bib",
            ),
            "citation_pool": bib_keys,
            "llm_task": "Build a taxonomy and contrast the proposed mechanism against cited method families.",
        },
        {
            "slot_id": "method_mechanism",
            "section": "methodology",
            "claim_type": "method_mechanism",
            "candidate_evidence": available(
                "ideation/hypotheses.md",
                "ideation/exp_plan.yaml",
                "ideation/idea_scorecard.yaml",
                "experiments/configs",
            ),
            "llm_task": "Explain the proposed mechanism and algorithmic procedure from hypotheses and exp_plan; tools do not infer the method.",
        },
        {
            "slot_id": "experiments_main_result",
            "section": "experiments",
            "claim_type": "empirical_result",
            "candidate_evidence": available(
                "experiments/results_summary.json",
                "experiments/ablations.csv",
                "experiments/seed_ensemble_summary.json",
                "experiments/iteration_log.md",
            ),
            "result_metric_candidates": metrics,
            "llm_task": "Report only metrics present in result artifacts and state seed/baseline context.",
        },
        {
            "slot_id": "analysis_mechanism_evidence",
            "section": "analysis",
            "claim_type": "mechanism_interpretation",
            "candidate_evidence": available(
                "experiments/ablations.csv",
                "experiments/iteration_log.md",
                "ideation/novelty_audit.md",
            ),
            "llm_task": "Interpret why ablations support or weaken the claimed mechanism; note alternative explanations.",
        },
        {
            "slot_id": "limitations_boundary",
            "section": "limitations",
            "claim_type": "evidence_boundary",
            "candidate_evidence": available(
                "ideation/risks.md",
                "ideation/novelty_audit.md",
                "experiments/iteration_log.md",
                "novelty/novelty_report.md",
            ),
            "llm_task": "State direct-full, skipped T5/T6, data, baseline, and reproducibility boundaries honestly.",
        },
    ]

    evidence_plan = {
        "version": "1.0",
        "target_venue": target_venue,
        "semantics": "mechanical_claim_slots_not_final_claims",
        "claim_slots": claim_slots,
        "global_evidence_inventory": {
            "artifacts": sorted(artifact_paths),
            "bib_keys": bib_keys,
            "result_metrics": metrics,
            "ablation_columns": index.get("ablation_columns", []),
            "figures": figures,
            "tables": tables,
        },
        "rules": [
            "LLM must fill claim wording; this plan only lists slots and provenance.",
            "Every numeric claim must point to result_metrics or an experiment artifact.",
            "Every citation claim must use keys from bib_keys.",
            "Unsupported slots must be marked as TODO or limitation, not invented.",
        ],
    }

    figure_slots = [
        {
            "figure_id": "fig:method_overview",
            "type": "schematic",
            "status": "needs_llm_or_code_generation",
            "source_artifacts": available("ideation/exp_plan.yaml", "ideation/hypotheses.md"),
            "intended_section": "methodology",
            "message_slot": "method_mechanism",
            "notes": "A method schematic is useful when the proposed mechanism has multiple steps; generate only if it clarifies the method.",
        },
        {
            "figure_id": "fig:main_results",
            "type": "result_plot",
            "status": "available_or_generate_from_results",
            "source_artifacts": available("experiments/results_summary.json", "experiments/runs"),
            "intended_section": "experiments",
            "message_slot": "experiments_main_result",
            "notes": "Plot headline metric vs. strongest baselines when result artifacts contain comparable runs.",
        },
        {
            "figure_id": "fig:ablation",
            "type": "ablation_plot",
            "status": "available_or_generate_from_csv",
            "source_artifacts": available("experiments/ablations.csv"),
            "intended_section": "analysis",
            "message_slot": "analysis_mechanism_evidence",
            "notes": "Use ablation CSV to visualize which mechanism component drives the effect.",
        },
        {
            "table_id": "tab:main_results",
            "type": "result_table",
            "status": "generate_from_results",
            "source_artifacts": available("experiments/results_summary.json"),
            "intended_section": "experiments",
            "message_slot": "experiments_main_result",
            "notes": "Prefer a compact table when baselines, metrics, and seed statistics are clearer than a plot.",
        },
        {
            "table_id": "tab:related_work",
            "type": "comparison_table",
            "status": "derive_from_literature_table",
            "source_artifacts": available("literature/comparison_table.csv", "literature/synthesis.md"),
            "intended_section": "related_work",
            "message_slot": "related_work_positioning",
            "notes": "Use only verified comparison fields; do not imply absent prior-work properties.",
        },
    ]

    figure_plan = {
        "version": "1.0",
        "target_venue": target_venue,
        "semantics": "mechanical_figure_table_plan_not_generated_figures",
        "existing_figures": figures,
        "existing_tables": tables,
        "planned_visuals": figure_slots,
        "generation_guidance": [
            "Generate plots from results/ablations/run artifacts, not from manuscript prose.",
            "Captions must state data source and metric definitions.",
            "Use accessible colors and avoid overloaded multi-metric figures.",
            "If data is missing, leave the planned visual as TODO and explain the limitation.",
        ],
    }
    return evidence_plan, figure_plan


def normalize_section_id(section_id: str) -> str:
    key = section_id.strip().lower().replace(" ", "_")
    return SECTION_ALIASES.get(key, key)


def build_paper_state(
    *,
    outline_path: str,
    outline_text: str,
    index: dict[str, Any],
    section_plan: dict[str, Any],
    evidence_plan: dict[str, Any],
    figure_plan: dict[str, Any],
    section_outline_dir: str,
    target_venue: str,
) -> dict[str, Any]:
    metrics = index.get("result_metrics", []) if isinstance(index, dict) else []
    bib_keys = index.get("bib_keys", []) if isinstance(index, dict) else []
    sections: dict[str, dict[str, Any]] = {}
    planned_sections = {
        normalize_section_id(str(item.get("id", ""))): item
        for item in section_plan.get("sections", [])
        if isinstance(item, dict) and item.get("id")
    } if isinstance(section_plan, dict) else {}
    for section_id in SECTION_WRITING_SEQUENCE:
        plan_entry = planned_sections.get(section_id, {})
        sections[section_id] = {
            "status": "pending",
            "file": f"drafts/sections/{section_id}.tex",
            "outline": f"{section_outline_dir.rstrip('/')}/{section_id}.md",
            "required_inputs": list(plan_entry.get("required_inputs", [])),
            "available_inputs": list(plan_entry.get("available_inputs", [])),
            "missing_inputs": list(plan_entry.get("missing_inputs", [])),
            "expected_outputs": list(plan_entry.get("expected_outputs", [])),
        }

    claim_slots = [
        {
            "slot_id": item.get("slot_id"),
            "section": normalize_section_id(str(item.get("section", ""))),
            "claim_type": item.get("claim_type"),
            "candidate_evidence": item.get("candidate_evidence", []),
            "result_metric_candidates": item.get("result_metric_candidates", []),
            "citation_pool": item.get("citation_pool", []),
        }
        for item in evidence_plan.get("claim_slots", [])
        if isinstance(item, dict)
    ] if isinstance(evidence_plan, dict) else []
    visuals = figure_plan.get("planned_visuals", []) if isinstance(figure_plan, dict) else []

    return {
        "version": "1.0",
        "semantics": "shared_state_for_section_by_section_writing_not_final_claims",
        "target_venue": target_venue,
        "outline": outline_path,
        "section_order": SECTION_WRITING_SEQUENCE,
        "sections": sections,
        "current_section": None,
        "last_written_section": None,
        "shared_facts": {
            "source": "mechanical_candidates_from_artifacts; Writer LLM must verify wording",
            "title_candidates": _extract_title_candidates(outline_text),
            "bib_keys": bib_keys,
            "result_metrics": metrics,
            "claim_slots": claim_slots,
            "planned_visuals": visuals,
        },
        "rules": [
            "Each T8-SEC-* task writes exactly one section file.",
            "Numbers must come from shared_facts.result_metrics or experiment artifacts.",
            "Citation keys must come from shared_facts.bib_keys.",
            "If a section needs a missing fact, read the source artifact and update the state with provenance rather than inventing it.",
            "Tools maintain state and assembly; LLM writes section prose and scientific reasoning.",
        ],
        "revision_log": [],
    }


def build_section_outlines(
    state: dict[str, Any],
    *,
    section_plan: dict[str, Any],
    evidence_plan: dict[str, Any],
    figure_plan: dict[str, Any],
    outline_text: str,
) -> dict[str, str]:
    plan_by_section = {
        normalize_section_id(str(item.get("id", ""))): item
        for item in section_plan.get("sections", [])
        if isinstance(item, dict) and item.get("id")
    } if isinstance(section_plan, dict) else {}
    slots_by_section: dict[str, list[dict[str, Any]]] = {}
    for item in evidence_plan.get("claim_slots", []) if isinstance(evidence_plan, dict) else []:
        if not isinstance(item, dict):
            continue
        slots_by_section.setdefault(normalize_section_id(str(item.get("section", ""))), []).append(item)
    visuals_by_section: dict[str, list[dict[str, Any]]] = {}
    for item in figure_plan.get("planned_visuals", []) if isinstance(figure_plan, dict) else []:
        if not isinstance(item, dict):
            continue
        visuals_by_section.setdefault(normalize_section_id(str(item.get("intended_section", ""))), []).append(item)

    outlines: dict[str, str] = {}
    for section_id in SECTION_WRITING_SEQUENCE:
        plan_entry = plan_by_section.get(section_id, {})
        local_outline = _extract_outline_section(outline_text, section_id)
        lines = [
            f"# Section Outline: {SECTION_TITLES.get(section_id, section_id)}",
            "",
            "## Purpose",
            _section_purpose(section_id),
            "",
            "## Global Outline Notes",
            local_outline or "- No explicit local outline found; use the global outline and section plan.",
            "",
            "## Required Inputs",
        ]
        for path in plan_entry.get("required_inputs", []):
            lines.append(f"- `{path}`")
        if not plan_entry.get("required_inputs"):
            lines.append("- See `drafts/paper_state.json` and `drafts/section_plan.json`.")
        lines.extend(["", "## Expected Outputs"])
        for item in plan_entry.get("expected_outputs", []):
            lines.append(f"- {item}")
        if not plan_entry.get("expected_outputs"):
            lines.append("- Section prose that advances the paper argument without whole-document wrapper.")
        lines.extend(["", "## Claim Slots"])
        for slot in slots_by_section.get(section_id, []):
            lines.append(
                "- `{}` ({}) evidence={} citations={}".format(
                    slot.get("slot_id"),
                    slot.get("claim_type", "claim"),
                    slot.get("candidate_evidence", []),
                    slot.get("citation_pool", []),
                )
            )
        if not slots_by_section.get(section_id):
            lines.append("- No direct claim slot; avoid adding unsupported new claims.")
        lines.extend(["", "## Figure/Table Slots"])
        for visual in visuals_by_section.get(section_id, []):
            vid = visual.get("figure_id") or visual.get("table_id") or "visual"
            lines.append(
                f"- `{vid}` status={visual.get('status')} sources={visual.get('source_artifacts', [])}"
            )
        if not visuals_by_section.get(section_id):
            lines.append("- No planned visual required for this section.")
        lines.extend(
            [
                "",
                "## Writing Rules",
                "- Write only this section.",
                "- Do not include `\\documentclass`, `\\begin{document}`, or `\\end{document}`.",
                "- Use only BibTeX keys and result numbers traceable through `paper_state.json` or source artifacts.",
                "- Mark unsupported material as TODO or limitation instead of inventing it.",
                "",
            ]
        )
        outlines[section_id] = "\n".join(lines)
    return outlines


def assemble_sections(section_dir: Path, *, title: str = "", target_venue: str = "", outline_text: str = "") -> str:
    if not section_dir.exists():
        raise FileNotFoundError(section_dir)
    section_texts: dict[str, str] = {}
    for name in CORE_SECTIONS:
        for suffix in (".tex", ".md"):
            path = section_dir / f"{name}{suffix}"
            if path.exists():
                section_texts[name] = _strip_document_wrappers(path.read_text(encoding="utf-8"))
                break
    missing = [name for name in CORE_SECTIONS if name not in section_texts and name not in {"analysis", "limitations"}]
    if missing:
        raise FileNotFoundError(f"missing section drafts: {', '.join(missing)}")

    title = title or _extract_title(outline_text) or "ResearchOS Manuscript Draft"
    body_parts = []
    abstract = section_texts.get("abstract", "").strip()
    for name in ["introduction", "related_work", "methodology", "experiments", "analysis", "limitations", "conclusion"]:
        text = section_texts.get(name, "").strip()
        if not text:
            continue
        if not re.search(r"\\section\*?\{", text):
            heading = _latex_section_title(name)
            text = f"\\section{{{heading}}}\n{text}"
        body_parts.append(text)

    return (
        "\\documentclass{article}\n"
        "\\usepackage{graphicx}\n"
        "\\usepackage{amsmath}\n"
        "\\usepackage{booktabs}\n"
        "\\usepackage{hyperref}\n"
        "\\begin{document}\n"
        f"\\title{{{_escape_latex_braces(title)}}}\n"
        "\\author{}\n"
        "\\maketitle\n"
        f"\\begin{{abstract}}\n{abstract}\n\\end{{abstract}}\n\n"
        + "\n\n".join(body_parts)
        + "\n\n\\bibliographystyle{plain}\n\\bibliography{related_work}\n"
        "\\end{document}\n"
    )


def audit_manuscript(paper: str, index: dict[str, Any]) -> str:
    bib_keys = set(index.get("bib_keys", []))
    cited = _extract_latex_cites(paper)
    missing_cites = sorted(cited - bib_keys)
    numbers = sorted(set(re.findall(r"(?<![A-Za-z])\d+(?:\.\d+)?\s*(?:%|x|×|ms|s|h|GPU-h)?", paper)))
    result_values = {
        str(item.get("value"))
        for item in index.get("result_metrics", [])
        if item.get("value") is not None
    }
    unsupported_numbers = [num for num in numbers if not any(num.strip().startswith(val) for val in result_values)]
    figure_refs = sorted(set(re.findall(r"\\ref\{fig:([^}]+)\}", paper)))
    table_refs = sorted(set(re.findall(r"\\ref\{tab:([^}]+)\}", paper)))
    section_titles = [title.lower() for title in re.findall(r"\\section\*?\{([^}]+)\}", paper)]
    section_aliases = {
        "Introduction": ["introduction"],
        "Related Work": ["related work", "literature review", "background"],
        "Method": ["method", "methodology", "approach", "model"],
        "Experiments": ["experiments", "evaluation", "results"],
        "Conclusion": ["conclusion", "conclusions"],
    }
    missing_sections = [
        sec
        for sec, aliases in section_aliases.items()
        if not any(alias in title for title in section_titles for alias in aliases)
    ]

    lines = ["# Manuscript Mechanical Audit", "", "该报告是机械审计 hint，不是最终学术判断。", ""]
    lines.append("## Citation Keys")
    if missing_cites:
        for key in missing_cites:
            lines.append(f"- [ ] Missing BibTeX key: `{key}`")
    else:
        lines.append("- [x] All detected citation keys exist in related_work.bib")

    lines.append("\n## Numeric Values")
    if unsupported_numbers:
        for num in unsupported_numbers[:30]:
            lines.append(f"- [ ] Verify numeric value appears in results artifacts or justify as non-result number: `{num}`")
    else:
        lines.append("- [x] Detected numeric values match indexed result values or no numbers detected")

    lines.append("\n## Figures And Tables")
    lines.append(f"- Detected figure refs: {figure_refs or 'none'}")
    lines.append(f"- Detected table refs: {table_refs or 'none'}")
    if not index.get("figures"):
        lines.append("- [ ] No figure files indexed; decide whether paper needs generated plots/schematics.")
    if not index.get("tables"):
        lines.append("- [ ] No table files indexed beyond CSV artifacts; ensure LaTeX tables are generated from results.")

    lines.append("\n## Required Sections")
    if missing_sections:
        for sec in missing_sections:
            lines.append(f"- [ ] Missing or nonstandard section: {sec}")
    else:
        lines.append("- [x] Core sections detected")
    lines.append("")
    return "\n".join(lines)


def build_revision_patch_list(
    *,
    round_num: int,
    review_text: str,
    section_reviews: dict[str, str],
    include_low: bool = True,
) -> dict[str, Any]:
    patches: list[dict[str, Any]] = []
    seen: set[tuple[str, str, str]] = set()

    for section_id in CORE_SECTIONS:
        text = section_reviews.get(section_id, "")
        for issue in _extract_review_issues(text, default_section=section_id):
            if issue["severity"] == "low" and not include_low:
                continue
            key = (issue["target_section"], issue["severity"], issue["specific_issue"][:160])
            if key in seen:
                continue
            seen.add(key)
            patches.append(issue)

    for issue in _extract_review_issues(review_text, default_section="global"):
        if issue["severity"] == "low" and not include_low:
            continue
        key = (issue["target_section"], issue["severity"], issue["specific_issue"][:160])
        if key in seen:
            continue
        seen.add(key)
        patches.append(issue)

    severity_rank = {"high": 0, "medium": 1, "low": 2}
    patches.sort(key=lambda item: (severity_rank.get(item["severity"], 3), _section_sort_key(item["target_section"])))
    for idx, patch in enumerate(patches, start=1):
        patch["patch_id"] = f"R{round_num}-P{idx:03d}"

    return {
        "version": "1.0",
        "semantics": "mechanical_review_issue_locations_not_final_revision_decisions",
        "round": round_num,
        "patches": patches,
        "rules": [
            "Patch list only localizes review issues; Writer LLM decides the actual academic revision.",
            "Prefer revising drafts/sections/<section>.tex, then reassemble drafts/paper.tex.",
            "Global patches may touch multiple sections, but should still be decomposed by the Writer when possible.",
            "Do not invent new results, citations, or claims while resolving patches.",
        ],
    }


def _extract_review_issues(text: str, *, default_section: str) -> list[dict[str, Any]]:
    if not text.strip():
        return []
    issues: list[dict[str, Any]] = []
    for line_no, line in enumerate(text.splitlines(), start=1):
        clean = line.strip()
        if not clean:
            continue
        severity = _detect_severity(clean)
        actionable_marker = bool(re.match(r"^[-*]\s*(?:\[[ xX]\]\s*)?", clean))
        heading_marker = clean.startswith("###") and ("问题" in clean or "issue" in clean.lower())
        if severity is None and not (actionable_marker or heading_marker):
            continue
        if severity is None:
            severity = "medium"
        issue_text = re.sub(r"^[-*]\s*(?:\[[ xX]\]\s*)?", "", clean).strip()
        issue_text = re.sub(r"^\[(?:High|Medium|Low|高|中|低)\]\s*", "", issue_text, flags=re.IGNORECASE)
        issue_text = re.sub(r"\*\*严重程度\*\*\s*[:：]\s*(High|Medium|Low)\s*", "", issue_text, flags=re.IGNORECASE).strip()
        if len(issue_text) < 8:
            continue
        section_id = _infer_section_from_text(issue_text, default_section=default_section)
        issues.append(
            {
                "patch_id": "",
                "target_section": section_id,
                "target_file": (
                    f"drafts/sections/{section_id}.tex" if section_id in CORE_SECTIONS else "drafts/paper.tex"
                ),
                "issue_type": _infer_issue_type(issue_text),
                "severity": severity,
                "specific_issue": issue_text[:1200],
                "suggested_action": "Revise the target section using source artifacts, paper_state.json, and reviewer context.",
                "source": {
                    "default_section": default_section,
                    "review_line": line_no,
                },
            }
        )
    return issues


def _detect_severity(text: str) -> str | None:
    low = text.lower()
    if re.search(r"\bhigh\b|严重程度\s*[:：]\s*高|\[高\]|高优先级", low):
        return "high"
    if re.search(r"\bmedium\b|严重程度\s*[:：]\s*中|\[中\]|中优先级", low):
        return "medium"
    if re.search(r"\blow\b|严重程度\s*[:：]\s*低|\[低\]|低优先级", low):
        return "low"
    if "major" in low or "主要问题" in text:
        return "high"
    if "minor" in low or "次要问题" in text:
        return "low"
    return None


def _infer_issue_type(text: str) -> str:
    low = text.lower()
    if any(token in low for token in ["citation", "\\cite", "bibtex", "引用", "文献"]):
        return "citation"
    if any(token in low for token in ["number", "metric", "数字", "指标", "result", "结果"]):
        return "factual"
    if any(token in low for token in ["evidence", "support", "证据", "支撑", "overclaim", "过度"]):
        return "missing_evidence"
    if any(token in low for token in ["clarity", "logic", "逻辑", "表达", "清晰", "过渡"]):
        return "clarity"
    if any(token in low for token in ["format", "latex", "格式"]):
        return "format"
    return "content"


def _infer_section_from_text(text: str, *, default_section: str) -> str:
    if default_section in CORE_SECTIONS:
        return default_section
    lowered = text.lower().replace("-", "_")
    aliases = [
        ("abstract", ["abstract", "摘要"]),
        ("introduction", ["introduction", "intro", "引言", "导言"]),
        ("related_work", ["related work", "related_work", "literature review", "相关工作", "文献综述"]),
        ("methodology", ["methodology", "method", "approach", "方法"]),
        ("experiments", ["experiments", "experiment", "evaluation", "results", "实验", "评估", "结果"]),
        ("analysis", ["analysis", "discussion", "分析", "讨论"]),
        ("limitations", ["limitations", "limitation", "局限"]),
        ("conclusion", ["conclusion", "结论"]),
    ]
    for section_id, names in aliases:
        if any(name in lowered or name in text for name in names):
            return section_id
    return "global"


def _section_sort_key(section_id: str) -> int:
    if section_id in CORE_SECTIONS:
        return CORE_SECTIONS.index(section_id)
    return len(CORE_SECTIONS)


def _artifact_entry(workspace: Path, path: Path, *, include_preview: bool) -> dict[str, Any]:
    rel = path.relative_to(workspace).as_posix()
    entry = {
        "path": rel,
        "kind": _artifact_kind(rel),
        "bytes": path.stat().st_size,
    }
    if include_preview and path.stat().st_size < 500_000:
        text = path.read_text(encoding="utf-8", errors="replace")
        entry["preview"] = text[:1200]
    return entry


def _read_optional_text(policy: WorkspaceAccessPolicy, rel_path: str) -> str:
    path = policy.workspace_dir / rel_path
    if not path.exists():
        return ""
    return policy.resolve_read(rel_path).read_text(encoding="utf-8", errors="replace")


def _read_optional_json(policy: WorkspaceAccessPolicy, rel_path: str) -> dict[str, Any]:
    text = _read_optional_text(policy, rel_path)
    if not text.strip():
        return {}
    data = json.loads(text)
    return data if isinstance(data, dict) else {}


def _artifact_kind(rel: str) -> str:
    if rel.endswith(".bib"):
        return "bibliography"
    if rel.endswith(".csv"):
        return "table_csv"
    if rel.endswith(".json"):
        return "json"
    if rel.endswith((".yaml", ".yml")):
        return "yaml"
    if rel.endswith(".md"):
        return "markdown"
    if rel.endswith(".py"):
        return "code"
    return "artifact"


def _glob_media(workspace: Path, *, kind: str) -> list[Path]:
    suffixes = {".png", ".jpg", ".jpeg", ".pdf", ".svg"} if kind == "figure" else {".csv", ".tsv", ".xlsx"}
    roots = [workspace / "experiments", workspace / "drafts", workspace / "evaluation"]
    paths: list[Path] = []
    for root in roots:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if path.is_file() and path.suffix.lower() in suffixes:
                paths.append(path)
    return sorted(paths)


def _media_entry(workspace: Path, path: Path) -> dict[str, Any]:
    return {
        "path": path.relative_to(workspace).as_posix(),
        "suffix": path.suffix.lower(),
        "bytes": path.stat().st_size,
    }


def _extract_bib_keys(path: Path) -> list[str]:
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8", errors="replace")
    return sorted(set(re.findall(r"@\w+\{([^,\s]+)", text)))


def _extract_latex_cites(text: str) -> set[str]:
    keys: set[str] = set()
    for chunk in re.findall(r"\\(?:cite|citep|citet|citealp|citealt|citeauthor|citeyear|parencite|textcite)\{([^}]+)\}", text):
        keys.update(key.strip() for key in chunk.split(",") if key.strip())
    return keys


def _extract_result_metrics(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return []
    metrics: list[dict[str, Any]] = []
    for exp in data.get("experiments", []) if isinstance(data, dict) else []:
        exp_id = exp.get("experiment_id") or exp.get("name") or "unknown"
        for key, value in (exp.get("metrics") or {}).items():
            if isinstance(value, (int, float, str)):
                metrics.append({"experiment_id": exp_id, "metric": key, "value": value})
    for path_key, value in _walk_numeric_values(data):
        if any(item["metric"] == path_key and item["value"] == value for item in metrics):
            continue
        metrics.append({"experiment_id": "results_summary", "metric": path_key, "value": value})
    return metrics


def _walk_numeric_values(value: Any, *, prefix: str = "") -> list[tuple[str, int | float]]:
    if isinstance(value, bool):
        return []
    if isinstance(value, (int, float)):
        return [(prefix or "value", value)]
    if isinstance(value, dict):
        found: list[tuple[str, int | float]] = []
        for key, child in value.items():
            child_prefix = f"{prefix}.{key}" if prefix else str(key)
            found.extend(_walk_numeric_values(child, prefix=child_prefix))
        return found
    if isinstance(value, list):
        found = []
        for idx, child in enumerate(value):
            child_prefix = f"{prefix}[{idx}]" if prefix else f"[{idx}]"
            found.extend(_walk_numeric_values(child, prefix=child_prefix))
        return found
    return []


def _csv_columns(path: Path) -> list[str]:
    if not path.exists():
        return []
    try:
        with path.open(newline="", encoding="utf-8") as handle:
            reader = csv.reader(handle)
            return next(reader, [])
    except Exception:
        return []


def _strip_document_wrappers(text: str) -> str:
    text = re.sub(r"\\documentclass(?:\[[^\]]+\])?\{[^}]+\}", "", text)
    text = re.sub(r"\\usepackage(?:\[[^\]]+\])?\{[^}]+\}", "", text)
    text = text.replace("\\begin{document}", "").replace("\\end{document}", "")
    return text.strip()


def _extract_title(outline_text: str) -> str:
    for line in outline_text.splitlines():
        clean = line.strip().lstrip("#").strip()
        if clean and "title" in clean.lower():
            parts = re.split(r"[:：]", clean, maxsplit=1)
            if len(parts) == 2 and parts[1].strip():
                return parts[1].strip()
    return ""


def _extract_title_candidates(outline_text: str) -> list[str]:
    candidates: list[str] = []
    for line in outline_text.splitlines():
        stripped = line.strip().lstrip("-*0123456789. ").strip()
        if not stripped:
            continue
        if "title" in stripped.lower() or "标题" in stripped:
            parts = re.split(r"[:：]", stripped, maxsplit=1)
            if len(parts) == 2 and parts[1].strip():
                candidates.append(parts[1].strip())
    return candidates[:5]


def _extract_outline_section(outline_text: str, section_id: str) -> str:
    if not outline_text.strip():
        return ""
    title = SECTION_TITLES.get(section_id, section_id).lower()
    aliases = {
        section_id.lower().replace("_", " "),
        title,
        "method" if section_id == "methodology" else "",
        "evaluation" if section_id == "experiments" else "",
        "literature review" if section_id == "related_work" else "",
        "discussion" if section_id == "analysis" else "",
    }
    aliases = {alias for alias in aliases if alias}
    lines = outline_text.splitlines()
    start = None
    for idx, line in enumerate(lines):
        stripped = line.strip().lstrip("#").strip().lower()
        if stripped and any(alias in stripped for alias in aliases):
            start = idx
            break
    if start is None:
        return ""
    end = len(lines)
    for idx in range(start + 1, len(lines)):
        if lines[idx].lstrip().startswith("##"):
            end = idx
            break
    return "\n".join(lines[start:end]).strip()[:4000]


def _section_purpose(section_id: str) -> str:
    return {
        "methodology": "Explain the proposed mechanism, algorithm/procedure, inputs, outputs, and implementation choices grounded in hypotheses and exp_plan.",
        "experiments": "Report setup, datasets, baselines, metrics, main results, ablations, seeds, and compute using only experiment artifacts.",
        "related_work": "Position the paper against prior work with a taxonomy and real citation keys from the bibliography.",
        "analysis": "Interpret mechanism evidence, ablations, alternative explanations, failure cases, and sensitivity.",
        "introduction": "Motivate the problem, define the gap, state the insight, contributions, and result headline without overclaiming.",
        "limitations": "State evidence boundaries, direct-full/T5/T6 skips, external validity, baseline coverage, and reproducibility limits.",
        "conclusion": "Recap contributions and future work without introducing new claims.",
        "abstract": "Compress the final paper into problem, method, evidence, result, and contribution after all sections exist.",
    }.get(section_id, "Write the section according to the global outline and evidence plan.")


def _latex_section_title(name: str) -> str:
    return {
        "related_work": "Related Work",
        "methodology": "Method",
        "experiments": "Experiments",
        "analysis": "Analysis",
        "limitations": "Limitations",
    }.get(name, name.replace("_", " ").title())


def _escape_latex_braces(text: str) -> str:
    return text.replace("{", "\\{").replace("}", "\\}")
