from __future__ import annotations

"""每个 task 的输入/输出 artifact 契约。

说明：
- 该文件主要服务于 single-task 调试模式、前置输入校验和 artifact 拷贝；
- 契约以 Agent Dev Spec 的模式 B I/O 表为主，同时遵守当前 runtime 使用 `state.yaml`
  的实现现实；
- HELLO 不是正式 T-stage，而是当前仓库已经跑通的最小 runtime 调试任务，因此也保留一份
  专用契约方便测试与 smoke run。
"""

from pathlib import Path


OPTIONAL_SEED_SURVEY_INPUTS: dict[str, str] = {
    "seed_outline_profile": "user_seeds/seed_outline_profile.json",
    "seed_ideas": "user_seeds/seed_ideas.md",
    "seed_constraints": "user_seeds/seed_constraints.md",
    "seed_external_resources": "user_seeds/seed_external_resources.jsonl",
}


TASK_IO_CONTRACTS: dict[str, dict[str, object]] = {
    "HELLO": {
        "inputs": {},
        "outputs": {"hello_file": "hello.txt"},
        "required_inputs": [],
        "schemas": {},
    },
    "T1": {
        "inputs": {},
        "outputs": {
            "project": "project.yaml",
            "state": "state.yaml",
            "bridge_domain_plan": "literature/bridge_domain_plan.json",
            # seed 文件是可选的，如果用户没有提供则可以不创建或创建空文件
        },
        "required_inputs": [],
        "schemas": {
            "project": "project",
            "bridge_domain_plan": "bridge_domain_plan",
        },
    },
    "T2-PARAM-GATE": {
        "inputs": {
            "project": "project.yaml",
            "seed_outline_profile": "user_seeds/seed_outline_profile.json",
            "bridge_domain_plan": "literature/bridge_domain_plan.json",
        },
        "outputs": {
            "literature_params": "literature/literature_params.json",
        },
        "required_inputs": ["project"],
        "schemas": {},
    },
    "T2-PARAM-CONFIRM-GATE": {
        "inputs": {
            "project": "project.yaml",
            "literature_params": "literature/literature_params.json",
            "seed_outline_profile": "user_seeds/seed_outline_profile.json",
            "bridge_domain_plan": "literature/bridge_domain_plan.json",
        },
        "outputs": {
            "literature_params_confirmation": "literature/literature_params_confirmation.json",
        },
        "required_inputs": ["project", "literature_params"],
        "schemas": {},
    },
    "T2": {
        "inputs": {
            "project": "project.yaml",
            "literature_params": "literature/literature_params.json",
            "literature_params_confirmation": "literature/literature_params_confirmation.json",
            "seed_papers": "user_seeds/seed_papers.jsonl",
            "seed_pdfs": "user_seeds/pdfs",
            "seed_constraints": "user_seeds/seed_constraints.md",
            "seed_ideas": "user_seeds/seed_ideas.md",
            "seed_outline_profile": "user_seeds/seed_outline_profile.json",
            "seed_external_resources": "user_seeds/seed_external_resources.jsonl",
            "bridge_domain_plan": "literature/bridge_domain_plan.json",
        },
        "outputs": {
            "papers_raw": "literature/papers_raw.jsonl",
            "papers_dedup": "literature/papers_dedup.jsonl",
            "papers_verified": "literature/papers_verified.jsonl",
            "papers_backlog": "literature/papers_backlog.jsonl",
            "verification_failures": "literature/verification_failures.jsonl",
            "citation_edges": "literature/citation_edges.json",
            "deep_read_queue": "literature/deep_read_queue.jsonl",
            "domain_map": "literature/domain_map.json",
            "access_audit": "literature/access_audit.md",
            "search_log": "literature/search_log.md",
            "missing_areas": "literature/missing_areas.md",
        },
        "required_inputs": ["project"],
        "schemas": {
            "papers_raw": "papers_raw",
            "papers_dedup": "papers_dedup",
            "papers_verified": "papers_verified",
            "papers_backlog": "papers_dedup",
            "verification_failures": "verification_failure",
            "deep_read_queue": "deep_read_queue",
            "domain_map": "domain_map",
        },
    },
    "T2-COVERAGE-GATE": {
        "inputs": {
            "search_log": "literature/search_log.md",
            "missing_areas": "literature/missing_areas.md",
            "domain_map": "literature/domain_map.json",
            "access_audit": "literature/access_audit.md",
            "deep_read_queue": "literature/deep_read_queue.jsonl",
        },
        "outputs": {
            "coverage_decision": "literature/coverage_decision.json",
        },
        "required_inputs": ["search_log", "missing_areas", "domain_map", "deep_read_queue"],
        "schemas": {},
    },
    "T3": {
        "inputs": {
            "project": "project.yaml",
            "papers_dedup": "literature/papers_dedup.jsonl",
            "papers_verified": "literature/papers_verified.jsonl",
            "papers_backlog": "literature/papers_backlog.jsonl",
            "deep_read_queue": "literature/deep_read_queue.jsonl",
            "deep_read_queue_pending": "literature/deep_read_queue_pending.jsonl",
            "domain_map": "literature/domain_map.json",
            "access_audit": "literature/access_audit.md",
            "missing_areas": "literature/missing_areas.md",
            "seed_outline_profile": "user_seeds/seed_outline_profile.json",
            "seed_constraints": "user_seeds/seed_constraints.md",
            "seed_external_resources": "user_seeds/seed_external_resources.jsonl",
        },
        "outputs": {
            "paper_notes_dir": "literature/paper_notes",
            "comparison_table": "literature/comparison_table.csv",
            "related_work_bib": "literature/related_work.bib",
            "paper_notes_abstract_dir": "literature/paper_notes_abstract",
            "metadata_triage_report": "literature/metadata_triage.md",
        },
        "optional_outputs": ["paper_notes_abstract_dir", "metadata_triage_report"],
        "required_inputs": ["project", "papers_dedup"],
        "schemas": {},
    },
    "T3.5": {
        "inputs": {
            "project": "project.yaml",
            "paper_notes_dir": "literature/paper_notes",
            "comparison_table": "literature/comparison_table.csv",
            "missing_areas": "literature/missing_areas.md",
            "domain_map": "literature/domain_map.json",
            "paper_notes_abstract_dir": "literature/paper_notes_abstract",
            "metadata_triage_report": "literature/metadata_triage.md",
        },
        "outputs": {
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "synthesis_outline": "literature/synthesis_outline.md",
            "synthesis_draft": "literature/synthesis_draft.md",
        },
        "required_inputs": ["project", "paper_notes_dir", "comparison_table", "domain_map"],
        "schemas": {},
    },
    "T3.6-GATE-SURVEY": {
        "inputs": {
            "project": "project.yaml",
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "comparison_table": "literature/comparison_table.csv",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"survey_decision": "drafts/survey/decision.json"},
        "required_inputs": ["project", "synthesis", "synthesis_workbench", "domain_map"],
        "schemas": {},
    },
    "T3.6-TEMPLATE-GATE": {
        "inputs": {
            "project": "project.yaml",
            "survey_decision": "drafts/survey/decision.json",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"writing_template": "drafts/survey/writing_template.json"},
        "required_inputs": ["project", "survey_decision"],
        "schemas": {},
    },
    "T3.6-PLAN": {
        "inputs": {
            "project": "project.yaml",
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "comparison_table": "literature/comparison_table.csv",
            "paper_notes_dir": "literature/paper_notes",
            "paper_notes_abstract_dir": "literature/paper_notes_abstract",
            "related_work_bib": "literature/related_work.bib",
            "writing_template": "drafts/survey/writing_template.json",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"survey_plan": "drafts/survey/survey_plan.json"},
        "required_inputs": [
            "project",
            "synthesis",
            "synthesis_workbench",
            "domain_map",
            "comparison_table",
            "paper_notes_dir",
        ],
        "schemas": {},
    },
    "T3.6-GATE-OUTLINE": {
        "inputs": {
            "project": "project.yaml",
            "survey_plan": "drafts/survey/survey_plan.json",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {
            "survey_plan": "drafts/survey/survey_plan.json",
            "outline_decision": "drafts/survey/outline_decision.json",
        },
        "required_inputs": ["project", "survey_plan"],
        "schemas": {},
    },
    "T3.6-GATE-CORPUS": {
        "inputs": {
            "project": "project.yaml",
            "survey_plan": "drafts/survey/survey_plan.json",
            "paper_notes_dir": "literature/paper_notes",
            "paper_notes_abstract_dir": "literature/paper_notes_abstract",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"corpus_decision": "drafts/survey/corpus_decision.json"},
        "required_inputs": ["project", "survey_plan"],
        "schemas": {},
    },
    "T3.6-EXPAND": {
        "inputs": {
            "project": "project.yaml",
            "survey_plan": "drafts/survey/survey_plan.json",
            "corpus_decision": "drafts/survey/corpus_decision.json",
            "domain_map": "literature/domain_map.json",
            "papers_verified": "literature/papers_verified.jsonl",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"survey_expansion": "drafts/survey/survey_expansion.json"},
        "required_inputs": ["project", "survey_plan", "corpus_decision"],
        "schemas": {},
    },
    "T3.6-STATE": {
        "inputs": {
            "project": "project.yaml",
            "survey_plan": "drafts/survey/survey_plan.json",
            "corpus_decision": "drafts/survey/corpus_decision.json",
            "survey_expansion": "drafts/survey/survey_expansion.json",
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "comparison_table": "literature/comparison_table.csv",
            "related_work_bib": "literature/related_work.bib",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {
            "survey_state": "drafts/survey/survey_state.json",
            "survey_section_outlines_dir": "drafts/survey/section_outlines",
        },
        "required_inputs": ["project", "survey_plan", "corpus_decision", "synthesis", "domain_map"],
        "schemas": {},
    },
    "T3.6-SEC-BACKGROUND": {
        "inputs": {
            "project": "project.yaml",
            "survey_state": "drafts/survey/survey_state.json",
            "section_outline": "drafts/survey/section_outlines/background.md",
            "synthesis": "literature/synthesis.md",
            "domain_map": "literature/domain_map.json",
            "comparison_table": "literature/comparison_table.csv",
            "related_work_bib": "literature/related_work.bib",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"section": "drafts/survey/sections/background.tex"},
        "required_inputs": ["project", "survey_state", "section_outline", "synthesis", "related_work_bib"],
        "schemas": {},
    },
    "T3.6-SEC-TAXONOMY": {
        "inputs": {
            "project": "project.yaml",
            "survey_state": "drafts/survey/survey_state.json",
            "section_outline": "drafts/survey/section_outlines/taxonomy.md",
            "survey_plan": "drafts/survey/survey_plan.json",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "related_work_bib": "literature/related_work.bib",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"section": "drafts/survey/sections/taxonomy.tex"},
        "required_inputs": ["project", "survey_state", "section_outline", "survey_plan", "domain_map", "related_work_bib"],
        "schemas": {},
    },
    "T3.6-SEC-THEME-1": {
        "inputs": {
            "project": "project.yaml",
            "survey_state": "drafts/survey/survey_state.json",
            "survey_plan": "drafts/survey/survey_plan.json",
            "section_outline": "drafts/survey/section_outlines/theme_1.md",
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "comparison_table": "literature/comparison_table.csv",
            "paper_notes_dir": "literature/paper_notes",
            "paper_notes_abstract_dir": "literature/paper_notes_abstract",
            "related_work_bib": "literature/related_work.bib",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"section": "drafts/survey/sections/theme_1.tex"},
        "optional_outputs": ["section"],
        "required_inputs": ["project", "survey_state", "survey_plan", "section_outline", "synthesis", "related_work_bib"],
        "schemas": {},
    },
    "T3.6-SEC-THEME-2": {
        "inputs": {
            "project": "project.yaml",
            "survey_state": "drafts/survey/survey_state.json",
            "survey_plan": "drafts/survey/survey_plan.json",
            "section_outline": "drafts/survey/section_outlines/theme_2.md",
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "comparison_table": "literature/comparison_table.csv",
            "paper_notes_dir": "literature/paper_notes",
            "paper_notes_abstract_dir": "literature/paper_notes_abstract",
            "related_work_bib": "literature/related_work.bib",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"section": "drafts/survey/sections/theme_2.tex"},
        "optional_outputs": ["section"],
        "required_inputs": ["project", "survey_state", "survey_plan", "section_outline", "synthesis", "related_work_bib"],
        "schemas": {},
    },
    "T3.6-SEC-THEME-3": {
        "inputs": {
            "project": "project.yaml",
            "survey_state": "drafts/survey/survey_state.json",
            "survey_plan": "drafts/survey/survey_plan.json",
            "section_outline": "drafts/survey/section_outlines/theme_3.md",
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "comparison_table": "literature/comparison_table.csv",
            "paper_notes_dir": "literature/paper_notes",
            "paper_notes_abstract_dir": "literature/paper_notes_abstract",
            "related_work_bib": "literature/related_work.bib",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"section": "drafts/survey/sections/theme_3.tex"},
        "optional_outputs": ["section"],
        "required_inputs": ["project", "survey_state", "survey_plan", "section_outline", "synthesis", "related_work_bib"],
        "schemas": {},
    },
    "T3.6-SEC-THEME-4": {
        "inputs": {
            "project": "project.yaml",
            "survey_state": "drafts/survey/survey_state.json",
            "survey_plan": "drafts/survey/survey_plan.json",
            "section_outline": "drafts/survey/section_outlines/theme_4.md",
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "comparison_table": "literature/comparison_table.csv",
            "paper_notes_dir": "literature/paper_notes",
            "paper_notes_abstract_dir": "literature/paper_notes_abstract",
            "related_work_bib": "literature/related_work.bib",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"section": "drafts/survey/sections/theme_4.tex"},
        "optional_outputs": ["section"],
        "required_inputs": ["project", "survey_state", "survey_plan", "section_outline", "synthesis", "related_work_bib"],
        "schemas": {},
    },
    "T3.6-SEC-COMPARISON": {
        "inputs": {
            "project": "project.yaml",
            "survey_state": "drafts/survey/survey_state.json",
            "section_outline": "drafts/survey/section_outlines/comparison.md",
            "comparison_table": "literature/comparison_table.csv",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "related_work_bib": "literature/related_work.bib",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"section": "drafts/survey/sections/comparison.tex"},
        "required_inputs": ["project", "survey_state", "section_outline", "comparison_table", "related_work_bib"],
        "schemas": {},
    },
    "T3.6-SEC-CHALLENGES": {
        "inputs": {
            "project": "project.yaml",
            "survey_state": "drafts/survey/survey_state.json",
            "section_outline": "drafts/survey/section_outlines/challenges.md",
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "related_work_bib": "literature/related_work.bib",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"section": "drafts/survey/sections/challenges.tex"},
        "required_inputs": ["project", "survey_state", "section_outline", "synthesis", "related_work_bib"],
        "schemas": {},
    },
    "T3.6-SEC-FUTURE": {
        "inputs": {
            "project": "project.yaml",
            "survey_state": "drafts/survey/survey_state.json",
            "section_outline": "drafts/survey/section_outlines/future.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "related_work_bib": "literature/related_work.bib",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"section": "drafts/survey/sections/future.tex"},
        "required_inputs": ["project", "survey_state", "section_outline", "synthesis_workbench", "domain_map", "related_work_bib"],
        "schemas": {},
    },
    "T3.6-SEC-INTRO": {
        "inputs": {
            "project": "project.yaml",
            "survey_state": "drafts/survey/survey_state.json",
            "section_outline": "drafts/survey/section_outlines/introduction.md",
            "background_section": "drafts/survey/sections/background.tex",
            "taxonomy_section": "drafts/survey/sections/taxonomy.tex",
            "comparison_section": "drafts/survey/sections/comparison.tex",
            "challenges_section": "drafts/survey/sections/challenges.tex",
            "future_section": "drafts/survey/sections/future.tex",
            "related_work_bib": "literature/related_work.bib",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"section": "drafts/survey/sections/introduction.tex"},
        "required_inputs": [
            "project",
            "survey_state",
            "section_outline",
            "background_section",
            "taxonomy_section",
            "comparison_section",
            "challenges_section",
            "future_section",
        ],
        "schemas": {},
    },
    "T3.6-SEC-CONCLUSION": {
        "inputs": {
            "project": "project.yaml",
            "survey_state": "drafts/survey/survey_state.json",
            "section_outline": "drafts/survey/section_outlines/conclusion.md",
            "challenges_section": "drafts/survey/sections/challenges.tex",
            "future_section": "drafts/survey/sections/future.tex",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"section": "drafts/survey/sections/conclusion.tex"},
        "required_inputs": ["project", "survey_state", "section_outline", "challenges_section", "future_section"],
        "schemas": {},
    },
    "T3.6-SEC-ABSTRACT": {
        "inputs": {
            "project": "project.yaml",
            "survey_state": "drafts/survey/survey_state.json",
            "section_outline": "drafts/survey/section_outlines/abstract.md",
            "introduction_section": "drafts/survey/sections/introduction.tex",
            "taxonomy_section": "drafts/survey/sections/taxonomy.tex",
            "comparison_section": "drafts/survey/sections/comparison.tex",
            "challenges_section": "drafts/survey/sections/challenges.tex",
            "future_section": "drafts/survey/sections/future.tex",
            "conclusion_section": "drafts/survey/sections/conclusion.tex",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {"section": "drafts/survey/sections/abstract.tex"},
        "required_inputs": [
            "project",
            "survey_state",
            "section_outline",
            "introduction_section",
            "taxonomy_section",
            "comparison_section",
            "challenges_section",
            "future_section",
            "conclusion_section",
        ],
        "schemas": {},
    },
    "T3.6-ASSEMBLE": {
        "inputs": {
            "project": "project.yaml",
            "survey_state": "drafts/survey/survey_state.json",
            "sections_dir": "drafts/survey/sections",
            "survey_plan": "drafts/survey/survey_plan.json",
            "related_work_bib": "literature/related_work.bib",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {
            "survey_tex": "drafts/survey/survey.tex",
            "survey_audit": "drafts/survey/survey_audit.md",
            "survey_audit_json": "drafts/survey/survey_audit.json",
        },
        "required_inputs": ["project", "survey_state", "sections_dir", "survey_plan", "related_work_bib"],
        "schemas": {},
    },
    "T3.6-REVIEW": {
        "inputs": {
            "project": "project.yaml",
            "survey_plan": "drafts/survey/survey_plan.json",
            "survey_state": "drafts/survey/survey_state.json",
            "survey_tex": "drafts/survey/survey.tex",
            "survey_audit": "drafts/survey/survey_audit.md",
            "survey_audit_json": "drafts/survey/survey_audit.json",
            "sections_dir": "drafts/survey/sections",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "comparison_table": "literature/comparison_table.csv",
            "related_work_bib": "literature/related_work.bib",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {
            "survey_review": "drafts/survey/survey_review.md",
            "survey_review_actions": "drafts/survey/survey_review_actions.json",
            "survey_tex": "drafts/survey/survey.tex",
            "survey_audit": "drafts/survey/survey_audit.md",
            "survey_audit_json": "drafts/survey/survey_audit.json",
        },
        "required_inputs": [
            "project",
            "survey_plan",
            "survey_state",
            "survey_tex",
            "survey_audit_json",
            "sections_dir",
            "synthesis_workbench",
            "domain_map",
            "comparison_table",
        ],
        "schemas": {},
    },
    "T3.6-COMPILE": {
        "inputs": {
            "project": "project.yaml",
            "survey_tex": "drafts/survey/survey.tex",
            "references_bib": "drafts/survey/references.bib",
            "survey_audit_json": "drafts/survey/survey_audit.json",
            "survey_review_actions": "drafts/survey/survey_review_actions.json",
        },
        "outputs": {
            "survey_pdf": "drafts/survey/survey.pdf",
            "survey_log": "drafts/survey/survey.log",
            "survey_compile_report": "drafts/survey/survey_compile_report.json",
        },
        "required_inputs": ["project", "survey_tex", "references_bib", "survey_audit_json", "survey_review_actions"],
        "schemas": {},
    },
    "T3.6-FEED": {
        "inputs": {
            "project": "project.yaml",
            "survey_plan": "drafts/survey/survey_plan.json",
            "survey_state": "drafts/survey/survey_state.json",
            "survey_tex": "drafts/survey/survey.tex",
            "survey_audit_json": "drafts/survey/survey_audit.json",
            "survey_compile_report": "drafts/survey/survey_compile_report.json",
            **OPTIONAL_SEED_SURVEY_INPUTS,
        },
        "outputs": {
            "survey_insights": "ideation/survey_insights.json",
            "survey_summary": "drafts/survey/survey_summary.md",
        },
        "required_inputs": [
            "project",
            "survey_plan",
            "survey_state",
            "survey_tex",
            "survey_audit_json",
            "survey_compile_report",
        ],
        "schemas": {},
    },
    "T4": {
        "inputs": {
            "project": "project.yaml",
            "synthesis": "literature/synthesis.md",
            "comparison_table": "literature/comparison_table.csv",
            "missing_areas": "literature/missing_areas.md",
            "domain_map": "literature/domain_map.json",
            "bridge_domain_plan": "literature/bridge_domain_plan.json",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "survey_insights": "ideation/survey_insights.json",
            "seed_ideas": "user_seeds/seed_ideas.md",
            "seed_constraints": "user_seeds/seed_constraints.md",
        },
        "outputs": {
            "hypotheses": "ideation/hypotheses.md",
            "exp_plan": "ideation/exp_plan.yaml",
            "risks": "ideation/risks.md",
            "idea_rationales": "ideation/idea_rationales.json",
            "idea_scorecard": "ideation/idea_scorecard.yaml",
            "rejected_ideas": "ideation/rejected_ideas.md",
            "gate_decisions": "ideation/gate_decisions.json",
            "family_distribution": "ideation/_family_distribution.md",
            "pass1_forward_candidates": "ideation/_pass1_forward_candidates.json",
            "pass2_grounding_review": "ideation/_pass2_grounding_review.json",
            "candidate_directions": "ideation/_candidate_directions.json",
            "gate1_candidate_cards": "ideation/_gate1_candidate_cards.md",
            "gate1_selection_brief": "ideation/_gate1_selection_brief.md",
            "bridge_coverage_review": "ideation/bridge_coverage_review.json",
            "selected_idea_brief": "ideation/selected_idea_brief.md",
        },
        "optional_outputs": ["bridge_coverage_review"],
        "required_inputs": ["project", "synthesis", "domain_map", "synthesis_workbench"],
        "schemas": {
            "exp_plan": "exp_plan",
            "idea_rationales": "idea_rationales",
            "idea_scorecard": "idea_scorecard",
            "gate_decisions": "gate_decisions",
            "bridge_coverage_review": "bridge_coverage_review",
        },
    },
    "T4-GATE1": {
        "inputs": {
            "candidate_directions": "ideation/_candidate_directions.json",
            "gate1_candidate_cards": "ideation/_gate1_candidate_cards.md",
            "gate1_selection_brief": "ideation/_gate1_selection_brief.md",
            "pass1_forward_candidates": "ideation/_pass1_forward_candidates.json",
            "pass2_grounding_review": "ideation/_pass2_grounding_review.json",
            "bridge_coverage_review": "ideation/bridge_coverage_review.json",
        },
        "outputs": {
            "gate1_user_selection": "ideation/_gate1_user_selection.json",
        },
        "optional_outputs": ["gate1_user_selection"],
        "required_inputs": [
            "candidate_directions",
            "gate1_candidate_cards",
            "gate1_selection_brief",
            "pass1_forward_candidates",
            "pass2_grounding_review",
        ],
        "schemas": {},
    },
    "T4.5": {
        "inputs": {
            "project": "project.yaml",
            "hypotheses": "ideation/hypotheses.md",
            "synthesis": "literature/synthesis.md",
            "comparison_table": "literature/comparison_table.csv",
            "idea_scorecard": "ideation/idea_scorecard.yaml",
        },
        "outputs": {
            "novelty_audit": "ideation/novelty_audit.md",
            "mechanism_tuples_dir": "ideation/_mechanism_tuples",
            "design_rationale_tuples_dir": "ideation/_design_rationale_tuples",
            "collision_cases": "ideation/collision_cases.md",
        },
        "optional_outputs": ["collision_cases"],
        "required_inputs": ["project", "hypotheses", "synthesis"],
        "schemas": {},
    },
    "T4.5-HUMAN-REVIEW": {
        "inputs": {
            "project": "project.yaml",
            "hypotheses": "ideation/hypotheses.md",
            "novelty_audit": "ideation/novelty_audit.md",
            "idea_scorecard": "ideation/idea_scorecard.yaml",
            "selected_idea_brief": "ideation/selected_idea_brief.md",
            "gate1_selection_brief": "ideation/_gate1_selection_brief.md",
            "rejected_ideas": "ideation/rejected_ideas.md",
        },
        "outputs": {
            "novelty_human_review": "ideation/novelty_human_review.json",
        },
        "required_inputs": ["project", "hypotheses", "novelty_audit", "idea_scorecard"],
        "schemas": {},
    },
    "T5-HANDOFF": {
        "inputs": {
            "project": "project.yaml",
            "hypotheses": "ideation/hypotheses.md",
            "exp_plan": "ideation/exp_plan.yaml",
            "risks": "ideation/risks.md",
            "novelty_audit": "ideation/novelty_audit.md",
            "idea_scorecard": "ideation/idea_scorecard.yaml",
            "synthesis": "literature/synthesis.md",
            "comparison_table": "literature/comparison_table.csv",
        },
        "outputs": {
            "handoff_pack": "external_executor/handoff_pack.json",
            "executor_prompt": "external_executor/executor_prompt.md",
            "expected_outputs_schema": "external_executor/expected_outputs_schema.json",
            "allowed_paths": "external_executor/allowed_paths.txt",
            "executor_selection": "external_executor/executor_selection.json",
            "input_manifest": "external_executor/input_manifest.json",
            "codex_prompt": "external_executor/codex_prompt.md",
            "claude_code_prompt": "external_executor/claude_code_prompt.md",
            "manual_instructions": "external_executor/manual_instructions.md",
            "agents_md": "external_executor/AGENTS.md",
            "claude_md": "external_executor/CLAUDE.md",
            "external_readme": "external_executor/README.md",
            "dir_guide": "external_executor/_DIR_GUIDE.md",
            "job_state": "external_executor/job_state.json",
            "expr_dir": "external_executor/expr",
            "skills_dir": "external_executor/skills",
            "skill_template_manifest": "external_executor/skills/template_manifest.json",
        },
        "required_inputs": [
            "project",
            "hypotheses",
            "exp_plan",
            "novelty_audit",
            "idea_scorecard",
            "synthesis",
        ],
        "schemas": {},
    },
    "T5-REBOOST-GATE": {
        "inputs": {
            "project": "project.yaml",
            "hypotheses": "ideation/hypotheses.md",
            "exp_plan": "ideation/exp_plan.yaml",
            "risks": "ideation/risks.md",
            "novelty_audit": "ideation/novelty_audit.md",
            "idea_scorecard": "ideation/idea_scorecard.yaml",
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "comparison_table": "literature/comparison_table.csv",
        },
        "outputs": {
            "handoff_pack": "external_executor/handoff_pack.json",
            "reboost_report": "external_executor/reboost_report.json",
        },
        "required_inputs": ["project", "hypotheses", "exp_plan", "novelty_audit", "synthesis"],
        "schemas": {},
    },
    "T5-EXPR-MATERIAL-GATE": {
        "inputs": {
            "handoff_pack": "external_executor/handoff_pack.json",
            "expected_outputs_schema": "external_executor/expected_outputs_schema.json",
            "expr_dir": "external_executor/expr",
            "agents_md": "external_executor/AGENTS.md",
        },
        "outputs": {
            "materials_gate_decision": "external_executor/expr/materials_gate_decision.json",
        },
        "required_inputs": ["handoff_pack", "expected_outputs_schema", "expr_dir", "agents_md"],
        "schemas": {},
    },
    "T5-SKILL-CUSTOMIZATION-GATE": {
        "inputs": {
            "handoff_pack": "external_executor/handoff_pack.json",
            "expected_outputs_schema": "external_executor/expected_outputs_schema.json",
            "allowed_paths": "external_executor/allowed_paths.txt",
            "skills_dir": "external_executor/skills",
            "skill_template_manifest": "external_executor/skills/template_manifest.json",
            "customization_skill": "external_executor/skills/skills_customization/SKILL.md",
            "agents_md": "external_executor/AGENTS.md",
        },
        "outputs": {
            "skill_customization_report": "external_executor/skills/customization_report.json",
        },
        "required_inputs": [
            "handoff_pack",
            "expected_outputs_schema",
            "allowed_paths",
            "skills_dir",
            "skill_template_manifest",
            "customization_skill",
            "agents_md",
        ],
        "schemas": {},
    },
    "T5-EXECUTOR-GATE": {
        "inputs": {
            "handoff_pack": "external_executor/handoff_pack.json",
            "expected_outputs_schema": "external_executor/expected_outputs_schema.json",
            "allowed_paths": "external_executor/allowed_paths.txt",
            "agents_md": "external_executor/AGENTS.md",
            "claude_md": "external_executor/CLAUDE.md",
        },
        "outputs": {
            "executor_selection": "external_executor/executor_selection.json",
        },
        "required_inputs": ["handoff_pack", "expected_outputs_schema", "allowed_paths"],
        "schemas": {},
    },
    "T5-EXTERNAL-WAIT": {
        "inputs": {
            "executor_selection": "external_executor/executor_selection.json",
            "handoff_pack": "external_executor/handoff_pack.json",
            "expected_outputs_schema": "external_executor/expected_outputs_schema.json",
            "allowed_paths": "external_executor/allowed_paths.txt",
            "result_pack": "external_executor/result_pack.json",
            "executor_status": "external_executor/executor_status.json",
        },
        "outputs": {
            "wait_acceptance_report": "external_executor/wait_acceptance_report.json",
        },
        "required_inputs": ["executor_selection", "handoff_pack", "expected_outputs_schema", "allowed_paths"],
        "schemas": {},
    },
    "T5-DRY-RUN": {
        "inputs": {
            "executor_selection": "external_executor/executor_selection.json",
            "handoff_pack": "external_executor/handoff_pack.json",
            "expected_outputs_schema": "external_executor/expected_outputs_schema.json",
        },
        "outputs": {
            "result_pack": "external_executor/result_pack.json",
            "executor_status": "external_executor/executor_status.json",
            "run_manifest": "external_executor/run_manifest.json",
            "heartbeat": "external_executor/heartbeat.json",
            "raw_results_dir": "external_executor/raw_results",
            "configs_dir": "external_executor/configs",
            "logs_dir": "external_executor/logs",
        },
        "required_inputs": ["executor_selection", "handoff_pack", "expected_outputs_schema"],
        "schemas": {},
    },
    "T7-INGEST": {
        "inputs": {
            "result_pack": "external_executor/result_pack.json",
            "executor_status": "external_executor/executor_status.json",
            "handoff_pack": "external_executor/handoff_pack.json",
        },
        "outputs": {
            "results_summary": "experiments/results_summary.json",
            "run_records": "experiments/run_records.jsonl",
            "evidence_index": "experiments/evidence_index.json",
            "ingest_report": "experiments/ingest_report.json",
        },
        "required_inputs": ["result_pack", "executor_status", "handoff_pack"],
        "schemas": {},
    },
    "T7-AUDIT": {
        "inputs": {
            "results_summary": "experiments/results_summary.json",
            "evidence_index": "experiments/evidence_index.json",
            "run_records": "experiments/run_records.jsonl",
            "exp_plan": "ideation/exp_plan.yaml",
            "novelty_audit": "ideation/novelty_audit.md",
        },
        "outputs": {
            "integrity_audit": "experiments/integrity_audit.json",
            "result_audit": "experiments/result_audit.json",
            "experiment_fairness_review": "experiments/experiment_fairness_review.md",
            "method_audit": "experiments/method_audit.json",
            "framework_figure_audit": "experiments/framework_figure_audit.json",
            "method_writing_resources": "drafts/method_writing_resources.json",
        },
        "required_inputs": ["results_summary", "evidence_index", "run_records"],
        "schemas": {},
    },
    "T7-POST-NOVELTY": {
        "inputs": {
            "hypotheses": "ideation/hypotheses.md",
            "exp_plan": "ideation/exp_plan.yaml",
            "novelty_audit": "ideation/novelty_audit.md",
            "required_baselines": "novelty/required_baselines.json",
            "result_pack": "external_executor/result_pack.json",
            "results_summary": "experiments/results_summary.json",
            "integrity_audit": "experiments/integrity_audit.json",
            "patch_log": "external_executor/patches/patch_log.jsonl",
            "repo_snapshot": "external_executor/repo_snapshot.json",
        },
        "outputs": {
            "post_experiment_novelty_check": "novelty/post_experiment_novelty_check.json",
            "post_experiment_collision_cases": "novelty/post_experiment_collision_cases.md",
        },
        "required_inputs": ["results_summary", "integrity_audit", "novelty_audit"],
        "schemas": {},
    },
    "T7-CLAIMS": {
        "inputs": {
            "results_summary": "experiments/results_summary.json",
            "integrity_audit": "experiments/integrity_audit.json",
            "evidence_index": "experiments/evidence_index.json",
            "exp_plan": "ideation/exp_plan.yaml",
            "hypotheses": "ideation/hypotheses.md",
            "novelty_audit": "ideation/novelty_audit.md",
        },
        "outputs": {
            "experimental_claims": "experiments/experimental_claims.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "iteration_log": "experiments/iteration_log.md",
            "must_not_claim": "drafts/must_not_claim.md",
            "claim_support_matrix": "drafts/claim_support_matrix.csv",
            "limitations_from_experiments": "drafts/limitations_from_experiments.md",
            "figure_table_evidence_map": "drafts/figure_table_evidence_map.json",
        },
        "required_inputs": ["results_summary", "integrity_audit", "evidence_index"],
        "schemas": {},
    },
    "T5": {
        "inputs": {
            "project": "project.yaml",
            "hypotheses": "ideation/hypotheses.md",
            "exp_plan": "ideation/exp_plan.yaml",
            "risks": "ideation/risks.md",
        },
        "outputs": {
            "pilot_plan": "pilot/pilot_plan.yaml",
            "pilot_code": "pilot/pilot_code",
            "pilot_results": "pilot/pilot_results.json",
            "motivation_validation": "pilot/motivation_validation.md",
        },
        "required_inputs": ["project", "hypotheses", "exp_plan"],
        "schemas": {
            "pilot_plan": "pilot_plan",
            "pilot_results": "pilot_results",
        },
    },
    "T6": {
        "inputs": {
            "project": "project.yaml",
            "hypotheses": "ideation/hypotheses.md",
            "exp_plan": "ideation/exp_plan.yaml",
            "pilot_results": "pilot/pilot_results.json",
            "motivation_validation": "pilot/motivation_validation.md",
            "novelty_audit": "ideation/novelty_audit.md",
            "comparison_table": "literature/comparison_table.csv",
            "synthesis": "literature/synthesis.md",
        },
        "outputs": {
            "novelty_report": "novelty/novelty_report.md",
            "collision_cases": "novelty/collision_cases.md",
            "must_add_baselines": "novelty/must_add_baselines.md",
        },
        "required_inputs": [
            "project",
            "hypotheses",
            "exp_plan",
            "pilot_results",
            "motivation_validation",
            "novelty_audit",
            "synthesis",
        ],
        "schemas": {},
    },
    "T7": {
        "inputs": {
            "project": "project.yaml",
            "hypotheses": "ideation/hypotheses.md",
            "exp_plan": "ideation/exp_plan.yaml",
            "risks": "ideation/risks.md",
            "novelty_audit": "ideation/novelty_audit.md",
            "idea_scorecard": "ideation/idea_scorecard.yaml",
            "synthesis": "literature/synthesis.md",
            "comparison_table": "literature/comparison_table.csv",
            "pilot_results": "pilot/pilot_results.json",
            "pilot_code": "pilot/pilot_code",
            "novelty_report": "novelty/novelty_report.md",
            "must_add_baselines": "novelty/must_add_baselines.md",
        },
        "outputs": {
            "results_summary": "experiments/results_summary.json",
            "runs_dir": "experiments/runs",
            "configs_dir": "experiments/configs",
            "iteration_log": "experiments/iteration_log.md",
            "ablations": "experiments/ablations.csv",
        },
        "required_inputs": [
            "project",
            "hypotheses",
            "exp_plan",
            "novelty_audit",
            "synthesis",
        ],
        "schemas": {
            "results_summary": "results_summary",
        },
    },
    "T7.5": {
        "inputs": {
            "results_summary": "experiments/results_summary.json",
            "iteration_log": "experiments/iteration_log.md",
            "integrity_audit": "experiments/integrity_audit.json",
            "experimental_claims": "experiments/experimental_claims.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "exp_plan": "ideation/exp_plan.yaml",
        },
        "outputs": {
            "evaluation_decision": "evaluation/evaluation_decision.md",
        },
        "required_inputs": ["results_summary", "integrity_audit", "result_to_claim", "experiment_evidence_pack"],
        "schemas": {},
    },
    "T8": {
        "inputs": {
            "project": "project.yaml",
            "writing_style": "drafts/writing_style.json",
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "paper_claim_audit": "drafts/paper_claim_audit.md",
            "related_work_bib": "literature/related_work.bib",
            "hypotheses": "ideation/hypotheses.md",
            "idea_scorecard": "ideation/idea_scorecard.yaml",
            "novelty_audit": "ideation/novelty_audit.md",
            "ablations": "experiments/ablations.csv",
        },
        "outputs": {
            "writing_style": "drafts/writing_style.json",
            "manuscript_resource_index": "drafts/manuscript_resource_index.json",
            "section_plan": "drafts/section_plan.json",
            "evidence_plan": "drafts/evidence_plan.json",
            "figure_table_plan": "drafts/figure_table_plan.json",
            "outline": "drafts/outline.md",
            "paper_state": "drafts/paper_state.json",
            "section_outlines_dir": "drafts/section_outlines",
            "sections_dir": "drafts/sections",
            "paper": "drafts/paper.tex",
            "manuscript_audit": "drafts/manuscript_audit.md",
            "craft_audit": "drafts/craft_audit.md",
            "paper_claim_audit": "drafts/paper_claim_audit.md",
            "paper_claim_audit_json": "drafts/paper_claim_audit.json",
            "alignment_matrix": "drafts/alignment_matrix.json",
            "self_check": "drafts/self_check.md",
        },
        "required_inputs": [
            "project",
            "synthesis",
            "synthesis_workbench",
            "domain_map",
            "writing_style",
            "related_work_bib",
            "hypotheses",
            "idea_scorecard",
            "results_summary",
        ],
        "schemas": {},
    },
    "T8-STYLE-GATE": {
        "inputs": {
            "project": "project.yaml",
        },
        "outputs": {
            "writing_style": "drafts/writing_style.json",
        },
        "required_inputs": ["project"],
        "schemas": {},
    },
    "T8-RESOURCE": {
        "inputs": {
            "project": "project.yaml",
            "writing_style": "drafts/writing_style.json",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "integrity_audit": "experiments/integrity_audit.json",
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "related_work_bib": "literature/related_work.bib",
            "hypotheses": "ideation/hypotheses.md",
            "exp_plan": "ideation/exp_plan.yaml",
            "novelty_audit": "ideation/novelty_audit.md",
            "idea_scorecard": "ideation/idea_scorecard.yaml",
            "comparison_table": "literature/comparison_table.csv",
            "ablations": "experiments/ablations.csv",
        },
        "outputs": {
            "manuscript_resource_index": "drafts/manuscript_resource_index.json",
            "section_plan": "drafts/section_plan.json",
            "evidence_plan": "drafts/evidence_plan.json",
            "figure_table_plan": "drafts/figure_table_plan.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "claim_ledger": "drafts/claim_ledger.json",
            "figure_registry": "drafts/figure_registry.json",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "required_inputs": [
            "project",
            "writing_style",
            "results_summary",
            "synthesis",
            "synthesis_workbench",
            "domain_map",
            "related_work_bib",
            "hypotheses",
            "idea_scorecard",
        ],
        "schemas": {},
    },
    "T8-WRITE": {
        "inputs": {
            "project": "project.yaml",
            "writing_style": "drafts/writing_style.json",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "related_work_bib": "literature/related_work.bib",
            "hypotheses": "ideation/hypotheses.md",
            "idea_scorecard": "ideation/idea_scorecard.yaml",
            "manuscript_resource_index": "drafts/manuscript_resource_index.json",
            "section_plan": "drafts/section_plan.json",
            "evidence_plan": "drafts/evidence_plan.json",
            "figure_table_plan": "drafts/figure_table_plan.json",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "claim_ledger": "drafts/claim_ledger.json",
            "figure_registry": "drafts/figure_registry.json",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {
            "outline": "drafts/outline.md",
        },
        "required_inputs": [
            "project",
            "writing_style",
            "results_summary",
            "synthesis",
            "synthesis_workbench",
            "domain_map",
            "related_work_bib",
            "hypotheses",
            "idea_scorecard",
            "manuscript_resource_index",
            "section_plan",
            "evidence_plan",
            "figure_table_plan",
            "cdr_claim_ledger",
            "claim_ledger",
            "figure_registry",
            "alignment_matrix",
        ],
        "schemas": {},
    },
    "T8-SECTION-PLAN": {
        "inputs": {
            "project": "project.yaml",
            "writing_style": "drafts/writing_style.json",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "integrity_audit": "experiments/integrity_audit.json",
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "related_work_bib": "literature/related_work.bib",
            "hypotheses": "ideation/hypotheses.md",
            "idea_scorecard": "ideation/idea_scorecard.yaml",
            "outline": "drafts/outline.md",
            "manuscript_resource_index": "drafts/manuscript_resource_index.json",
            "section_plan": "drafts/section_plan.json",
            "evidence_plan": "drafts/evidence_plan.json",
            "figure_table_plan": "drafts/figure_table_plan.json",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "claim_ledger": "drafts/claim_ledger.json",
            "figure_registry": "drafts/figure_registry.json",
            "alignment_matrix": "drafts/alignment_matrix.json",
            "ablations": "experiments/ablations.csv",
        },
        "outputs": {
            "paper_state": "drafts/paper_state.json",
            "section_outlines_dir": "drafts/section_outlines",
        },
        "required_inputs": [
            "project",
            "writing_style",
            "results_summary",
            "synthesis",
            "synthesis_workbench",
            "domain_map",
            "related_work_bib",
            "hypotheses",
            "idea_scorecard",
            "outline",
            "manuscript_resource_index",
            "section_plan",
            "evidence_plan",
            "figure_table_plan",
            "cdr_claim_ledger",
            "claim_ledger",
            "figure_registry",
            "alignment_matrix",
        ],
        "schemas": {},
    },
    "T8-SEC-METHOD": {
        "inputs": {
            "project": "project.yaml",
            "paper_state": "drafts/paper_state.json",
            "section_outline": "drafts/section_outlines/methodology.md",
            "hypotheses": "ideation/hypotheses.md",
            "exp_plan": "ideation/exp_plan.yaml",
            "idea_scorecard": "ideation/idea_scorecard.yaml",
            "novelty_audit": "ideation/novelty_audit.md",
            "design_rationale_tuples_dir": "ideation/_design_rationale_tuples",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "configs_dir": "experiments/configs",
            "code_dir": "experiments/code",
            "outline": "drafts/outline.md",
            "manuscript_resource_index": "drafts/manuscript_resource_index.json",
            "evidence_plan": "drafts/evidence_plan.json",
            "figure_table_plan": "drafts/figure_table_plan.json",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "claim_ledger": "drafts/claim_ledger.json",
            "figure_registry": "drafts/figure_registry.json",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {"section": "drafts/sections/methodology.tex"},
        "required_inputs": [
            "project",
            "paper_state",
            "section_outline",
            "hypotheses",
            "exp_plan",
            "idea_scorecard",
            "alignment_matrix",
        ],
        "schemas": {},
    },
    "T8-SEC-EXPERIMENTS": {
        "inputs": {
            "project": "project.yaml",
            "paper_state": "drafts/paper_state.json",
            "section_outline": "drafts/section_outlines/experiments.md",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "integrity_audit": "experiments/integrity_audit.json",
            "ablations": "experiments/ablations.csv",
            "exp_plan": "ideation/exp_plan.yaml",
            "seed_ensemble_summary": "experiments/seed_ensemble_summary.json",
            "runs_dir": "experiments/runs",
            "configs_dir": "experiments/configs",
            "must_add_baselines": "novelty/must_add_baselines.md",
            "manuscript_resource_index": "drafts/manuscript_resource_index.json",
            "evidence_plan": "drafts/evidence_plan.json",
            "figure_table_plan": "drafts/figure_table_plan.json",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "claim_ledger": "drafts/claim_ledger.json",
            "figure_registry": "drafts/figure_registry.json",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {"section": "drafts/sections/experiments.tex"},
        "required_inputs": [
            "project",
            "paper_state",
            "section_outline",
            "results_summary",
            "exp_plan",
            "figure_table_plan",
            "alignment_matrix",
        ],
        "schemas": {},
    },
    "T8-SEC-RELATED": {
        "inputs": {
            "project": "project.yaml",
            "paper_state": "drafts/paper_state.json",
            "section_outline": "drafts/section_outlines/related_work.md",
            "synthesis": "literature/synthesis.md",
            "synthesis_workbench": "literature/synthesis_workbench.json",
            "domain_map": "literature/domain_map.json",
            "related_work_bib": "literature/related_work.bib",
            "comparison_table": "literature/comparison_table.csv",
            "idea_scorecard": "ideation/idea_scorecard.yaml",
            "manuscript_resource_index": "drafts/manuscript_resource_index.json",
            "evidence_plan": "drafts/evidence_plan.json",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "claim_ledger": "drafts/claim_ledger.json",
            "figure_registry": "drafts/figure_registry.json",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {"section": "drafts/sections/related_work.tex"},
        "required_inputs": [
            "project",
            "paper_state",
            "section_outline",
            "synthesis",
            "synthesis_workbench",
            "domain_map",
            "related_work_bib",
            "idea_scorecard",
            "alignment_matrix",
        ],
        "schemas": {},
    },
    "T8-SEC-ANALYSIS": {
        "inputs": {
            "project": "project.yaml",
            "paper_state": "drafts/paper_state.json",
            "section_outline": "drafts/section_outlines/analysis.md",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "ablations": "experiments/ablations.csv",
            "iteration_log": "experiments/iteration_log.md",
            "novelty_audit": "ideation/novelty_audit.md",
            "methodology_section": "drafts/sections/methodology.tex",
            "experiments_section": "drafts/sections/experiments.tex",
            "manuscript_resource_index": "drafts/manuscript_resource_index.json",
            "evidence_plan": "drafts/evidence_plan.json",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "claim_ledger": "drafts/claim_ledger.json",
            "figure_registry": "drafts/figure_registry.json",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {"section": "drafts/sections/analysis.tex"},
        "required_inputs": [
            "project",
            "paper_state",
            "section_outline",
            "methodology_section",
            "experiments_section",
            "results_summary",
            "alignment_matrix",
        ],
        "schemas": {},
    },
    "T8-SEC-INTRO": {
        "inputs": {
            "project": "project.yaml",
            "paper_state": "drafts/paper_state.json",
            "section_outline": "drafts/section_outlines/introduction.md",
            "synthesis": "literature/synthesis.md",
            "hypotheses": "ideation/hypotheses.md",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "methodology_section": "drafts/sections/methodology.tex",
            "experiments_section": "drafts/sections/experiments.tex",
            "related_work_section": "drafts/sections/related_work.tex",
            "analysis_section": "drafts/sections/analysis.tex",
            "manuscript_resource_index": "drafts/manuscript_resource_index.json",
            "evidence_plan": "drafts/evidence_plan.json",
            "figure_table_plan": "drafts/figure_table_plan.json",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "claim_ledger": "drafts/claim_ledger.json",
            "figure_registry": "drafts/figure_registry.json",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {"section": "drafts/sections/introduction.tex"},
        "required_inputs": [
            "project",
            "paper_state",
            "section_outline",
            "methodology_section",
            "experiments_section",
            "related_work_section",
            "analysis_section",
            "synthesis",
            "hypotheses",
            "results_summary",
            "alignment_matrix",
        ],
        "schemas": {},
    },
    "T8-SEC-CONCLUSION": {
        "inputs": {
            "project": "project.yaml",
            "paper_state": "drafts/paper_state.json",
            "section_outline": "drafts/section_outlines/conclusion.md",
            "introduction_section": "drafts/sections/introduction.tex",
            "experiments_section": "drafts/sections/experiments.tex",
            "risks": "ideation/risks.md",
            "novelty_audit": "ideation/novelty_audit.md",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "iteration_log": "experiments/iteration_log.md",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "claim_ledger": "drafts/claim_ledger.json",
            "figure_registry": "drafts/figure_registry.json",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {"section": "drafts/sections/conclusion.tex"},
        "required_inputs": [
            "project",
            "paper_state",
            "section_outline",
            "introduction_section",
            "experiments_section",
            "risks",
            "novelty_audit",
            "results_summary",
            "alignment_matrix",
        ],
        "schemas": {},
    },
    "T8-SEC-ABSTRACT": {
        "inputs": {
            "project": "project.yaml",
            "paper_state": "drafts/paper_state.json",
            "section_outline": "drafts/section_outlines/abstract.md",
            "introduction_section": "drafts/sections/introduction.tex",
            "methodology_section": "drafts/sections/methodology.tex",
            "experiments_section": "drafts/sections/experiments.tex",
            "analysis_section": "drafts/sections/analysis.tex",
            "conclusion_section": "drafts/sections/conclusion.tex",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "claim_ledger": "drafts/claim_ledger.json",
            "figure_registry": "drafts/figure_registry.json",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {"section": "drafts/sections/abstract.tex"},
        "required_inputs": [
            "project",
            "paper_state",
            "section_outline",
            "introduction_section",
            "methodology_section",
            "experiments_section",
            "analysis_section",
            "conclusion_section",
            "alignment_matrix",
        ],
        "schemas": {},
    },
    "T8-SECTIONS": {
        "inputs": {
            "project": "project.yaml",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "integrity_audit": "experiments/integrity_audit.json",
            "synthesis": "literature/synthesis.md",
            "related_work_bib": "literature/related_work.bib",
            "hypotheses": "ideation/hypotheses.md",
            "outline": "drafts/outline.md",
            "manuscript_resource_index": "drafts/manuscript_resource_index.json",
            "section_plan": "drafts/section_plan.json",
            "evidence_plan": "drafts/evidence_plan.json",
            "figure_table_plan": "drafts/figure_table_plan.json",
            "ablations": "experiments/ablations.csv",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {
            "sections_dir": "drafts/sections",
        },
        "required_inputs": [
            "project",
            "results_summary",
            "synthesis",
            "related_work_bib",
            "hypotheses",
            "outline",
            "manuscript_resource_index",
            "section_plan",
            "evidence_plan",
            "figure_table_plan",
            "alignment_matrix",
        ],
        "schemas": {},
    },
    "T8-DRAFT": {
        "inputs": {
            "project": "project.yaml",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "integrity_audit": "experiments/integrity_audit.json",
            "synthesis": "literature/synthesis.md",
            "related_work_bib": "literature/related_work.bib",
            "hypotheses": "ideation/hypotheses.md",
            "novelty_audit": "ideation/novelty_audit.md",
            "ablations": "experiments/ablations.csv",
            "outline": "drafts/outline.md",
            "paper_state": "drafts/paper_state.json",
            "sections_dir": "drafts/sections",
            "manuscript_resource_index": "drafts/manuscript_resource_index.json",
            "section_plan": "drafts/section_plan.json",
            "evidence_plan": "drafts/evidence_plan.json",
            "figure_table_plan": "drafts/figure_table_plan.json",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "claim_ledger": "drafts/claim_ledger.json",
            "figure_registry": "drafts/figure_registry.json",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {
            "paper": "drafts/paper.tex",
            "manuscript_audit": "drafts/manuscript_audit.md",
            "craft_audit": "drafts/craft_audit.md",
            "paper_claim_audit": "drafts/paper_claim_audit.md",
            "paper_claim_audit_json": "drafts/paper_claim_audit.json",
        },
        "required_inputs": ["project", "results_summary", "outline", "paper_state", "sections_dir"],
        "schemas": {},
    },
    "T8-SELF-CHECK": {
        "inputs": {
            "project": "project.yaml",
            "paper": "drafts/paper.tex",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "paper_claim_audit": "drafts/paper_claim_audit.md",
            "synthesis": "literature/synthesis.md",
            "related_work_bib": "literature/related_work.bib",
            "ablations": "experiments/ablations.csv",
            "manuscript_resource_index": "drafts/manuscript_resource_index.json",
            "section_plan": "drafts/section_plan.json",
            "evidence_plan": "drafts/evidence_plan.json",
            "figure_table_plan": "drafts/figure_table_plan.json",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "claim_ledger": "drafts/claim_ledger.json",
            "figure_registry": "drafts/figure_registry.json",
            "manuscript_audit": "drafts/manuscript_audit.md",
            "craft_audit": "drafts/craft_audit.md",
            "paper_claim_audit": "drafts/paper_claim_audit.md",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {
            "self_check": "drafts/self_check.md",
        },
        "required_inputs": ["project", "paper", "results_summary", "related_work_bib"],
        "schemas": {},
    },
    "T8-REVIEW-1": {
        "inputs": {
            "project": "project.yaml",
            "paper": "drafts/paper.tex",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "paper_claim_audit": "drafts/paper_claim_audit.md",
            "related_work_bib": "literature/related_work.bib",
            "manuscript_audit": "drafts/manuscript_audit.md",
            "craft_audit": "drafts/craft_audit.md",
            "self_check": "drafts/self_check.md",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {
            "review_report": "drafts/review_rounds/round_1.md",
            "section_review_dir": "drafts/review_rounds/round_1_sections",
        },
        "required_inputs": ["project", "paper", "results_summary"],
        "schemas": {},
    },
    "T8-REVISE-1": {
        "inputs": {
            "project": "project.yaml",
            "paper": "drafts/paper.tex",
            "paper_state": "drafts/paper_state.json",
            "review_report": "drafts/review_rounds/round_1.md",
            "section_review_dir": "drafts/review_rounds/round_1_sections",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "paper_claim_audit": "drafts/paper_claim_audit.md",
            "synthesis": "literature/synthesis.md",
            "related_work_bib": "literature/related_work.bib",
            "ablations": "experiments/ablations.csv",
            "sections_dir": "drafts/sections",
            "manuscript_resource_index": "drafts/manuscript_resource_index.json",
            "evidence_plan": "drafts/evidence_plan.json",
            "figure_table_plan": "drafts/figure_table_plan.json",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "claim_ledger": "drafts/claim_ledger.json",
            "figure_registry": "drafts/figure_registry.json",
            "manuscript_audit": "drafts/manuscript_audit.md",
            "craft_audit": "drafts/craft_audit.md",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {
            "revision_patches": "drafts/patches/round_1_patches.json",
            "revision_response": "drafts/revision_response_round_1.md",
            "paper": "drafts/paper.tex",
            "manuscript_audit": "drafts/manuscript_audit.md",
            "craft_audit": "drafts/craft_audit.md",
            "paper_claim_audit": "drafts/paper_claim_audit.md",
            "paper_claim_audit_json": "drafts/paper_claim_audit.json",
        },
        "required_inputs": ["project", "paper", "paper_state", "review_report", "section_review_dir"],
        "schemas": {},
    },
    "T8-REVIEW-2": {
        "inputs": {
            "project": "project.yaml",
            "paper": "drafts/paper.tex",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "paper_claim_audit": "drafts/paper_claim_audit.md",
            "related_work_bib": "literature/related_work.bib",
            "manuscript_audit": "drafts/manuscript_audit.md",
            "craft_audit": "drafts/craft_audit.md",
            "previous_review": "drafts/review_rounds/round_1.md",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {
            "review_report": "drafts/review_rounds/round_2.md",
            "section_review_dir": "drafts/review_rounds/round_2_sections",
        },
        "required_inputs": ["project", "paper"],
        "schemas": {},
    },
    "T8-REVISE-2": {
        "inputs": {
            "project": "project.yaml",
            "paper": "drafts/paper.tex",
            "paper_state": "drafts/paper_state.json",
            "review_report": "drafts/review_rounds/round_2.md",
            "section_review_dir": "drafts/review_rounds/round_2_sections",
            "previous_review": "drafts/review_rounds/round_1.md",
            "results_summary": "experiments/results_summary.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "paper_claim_audit": "drafts/paper_claim_audit.md",
            "synthesis": "literature/synthesis.md",
            "related_work_bib": "literature/related_work.bib",
            "ablations": "experiments/ablations.csv",
            "sections_dir": "drafts/sections",
            "manuscript_resource_index": "drafts/manuscript_resource_index.json",
            "evidence_plan": "drafts/evidence_plan.json",
            "figure_table_plan": "drafts/figure_table_plan.json",
            "cdr_claim_ledger": "drafts/cdr_claim_ledger.json",
            "claim_ledger": "drafts/claim_ledger.json",
            "figure_registry": "drafts/figure_registry.json",
            "manuscript_audit": "drafts/manuscript_audit.md",
            "craft_audit": "drafts/craft_audit.md",
            "alignment_matrix": "drafts/alignment_matrix.json",
        },
        "outputs": {
            "revision_patches": "drafts/patches/round_2_patches.json",
            "revision_response": "drafts/revision_response_round_2.md",
            "paper": "drafts/paper.tex",
            "manuscript_audit": "drafts/manuscript_audit.md",
            "craft_audit": "drafts/craft_audit.md",
            "paper_claim_audit": "drafts/paper_claim_audit.md",
            "paper_claim_audit_json": "drafts/paper_claim_audit.json",
        },
        "required_inputs": ["project", "paper", "paper_state", "review_report", "section_review_dir"],
        "schemas": {},
    },
    "T8-PAPER-CLAIM-AUDIT": {
        "inputs": {
            "project": "project.yaml",
            "paper": "drafts/paper.tex",
            "result_to_claim": "drafts/result_to_claim.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
            "integrity_audit": "experiments/integrity_audit.json",
            "post_experiment_novelty_check": "novelty/post_experiment_novelty_check.json",
            "must_not_claim": "drafts/must_not_claim.md",
            "claim_ledger": "drafts/claim_ledger.json",
        },
        "outputs": {
            "paper_claim_audit": "drafts/paper_claim_audit.md",
            "paper_claim_audit_json": "drafts/paper_claim_audit.json",
        },
        "required_inputs": ["paper", "result_to_claim", "experiment_evidence_pack"],
        "schemas": {},
    },
    "T9": {
        "inputs": {
            "project": "project.yaml",
            "paper": "drafts/paper.tex",
            "related_work_bib": "literature/related_work.bib",
            "paper_claim_audit": "drafts/paper_claim_audit.md",
            "paper_claim_audit_json": "drafts/paper_claim_audit.json",
            "result_to_claim": "drafts/result_to_claim.json",
            "experiment_evidence_pack": "drafts/experiment_evidence_pack.json",
        },
        "outputs": {
            "bundle_dir": "submission/bundle",
            "migration_report": "submission/migration_report.md",
            "main_tex": "submission/bundle/main.tex",
            "references_bib": "submission/bundle/references.bib",
            "main_pdf": "submission/bundle/main.pdf",
            "compile_log": "submission/bundle/main.log",
            "compile_report": "submission/compile_report.json",
        },
        "required_inputs": ["project", "paper", "related_work_bib"],
        "optional_outputs": [],
    },
}


def get_task_io(task_id: str) -> dict[str, object]:
    """读取 task 的 I/O 契约。"""
    if task_id not in TASK_IO_CONTRACTS:
        raise KeyError(f"Unknown task I/O contract: {task_id}")
    return TASK_IO_CONTRACTS[task_id]


def resolve_outputs(workspace: Path, task_id: str) -> dict[str, Path]:
    """把 output 相对路径解析成 workspace 内绝对路径。"""
    contract = get_task_io(task_id)
    optional = set(contract.get("optional_outputs", []))
    outputs = {
        name: rel
        for name, rel in contract["outputs"].items()  # type: ignore[union-attr]
        if name not in optional
    }
    return {name: workspace / rel for name, rel in outputs.items()}


def resolve_inputs(workspace: Path, task_id: str) -> dict[str, Path]:
    """把 input 相对路径解析成 workspace 内绝对路径。"""
    inputs = get_task_io(task_id)["inputs"]
    return {name: workspace / rel for name, rel in inputs.items()}  # type: ignore[union-attr]


def required_input_names(task_id: str) -> list[str]:
    """返回某个 task 的必需前置输入 key 列表。

    兼容策略：
    - 若契约显式声明了 `required_inputs`，则严格使用它；
    - 若未来某个调试 task 只定义了 `inputs` 没定义 `required_inputs`，则保守退回成
      “所有输入都必需”，避免 single-task 模式误判可运行。
    """

    contract = get_task_io(task_id)
    required = contract.get("required_inputs")
    if required is None:
        inputs = contract.get("inputs", {})
        return list(inputs.keys())  # type: ignore[union-attr]
    return list(required)  # type: ignore[arg-type]
