from __future__ import annotations

from typing import Any


def default_resource_acquisition_policy() -> dict[str, Any]:
    """ResearchOS default authority for external executor resource preparation."""

    return {
        "mode": "github_and_reimplementation",
        "network_allowed": True,
        "github_access_allowed": True,
        "dataset_download_allowed": True,
        "baseline_reimplementation_allowed": True,
        "external_code_inspection_allowed": True,
        "authenticated_resources_allowed": False,
        "license_checks_required": True,
        "checksum_required": True,
        "citation_required": True,
        "allowed_domains": [
            "github.com",
            "raw.githubusercontent.com",
            "codeload.github.com",
            "objects.githubusercontent.com",
            "huggingface.co",
            "hf.co",
            "zenodo.org",
            "figshare.com",
            "kaggle.com",
            "openml.org",
            "archive.ics.uci.edu",
            "openreview.net",
            "gitlab.com",
            "bitbucket.org",
            "modelscope.cn",
            "www.modelscope.cn",
            "dataverse.harvard.edu",
            "datacite.org",
            "api.datacite.org",
            "codabench.org",
            "eval.ai",
            "evalai.cloudcv.org",
            "crfm.stanford.edu",
            "ogb.stanford.edu",
            "mteb-leaderboard.huggingface.co",
            "opencompass.org.cn",
        ],
        "remote_platform_priority": {
            "baseline": ["Hugging Face", "OpenReview", "GitLab", "Bitbucket", "ModelScope", "Zenodo"],
            "dataset": ["Hugging Face", "OpenML", "Kaggle", "UCI", "Zenodo", "Dataverse", "DataCite"],
            "benchmark": [
                "OpenML",
                "Hugging Face Leaderboards",
                "Codabench",
                "EvalAI",
                "HELM",
                "domain_specific_platforms",
            ],
        },
        "local_resource_roots": ["resources", "resource", "user_seeds"],
        "material_absence_policy": (
            "Do not inspect external_executor/expr for resource candidates. "
            "Use resources/ for by-hand local materials first, then public "
            "remote acquisition into resource/, then authorized baseline "
            "reimplementation into resource/."
        ),
        "prohibited_actions": [
            "bypass_authentication_or_clickthrough_terms",
            "expose_secrets_or_private_paths",
            "execute_unreviewed_third_party_installers",
            "claim_official_status_for_executor_reimplementations",
        ],
    }


def default_executor_capabilities(selected_executor: str) -> dict[str, Any]:
    real_executor = selected_executor in {"codex_cli", "claude_code_window", "manual"}
    return {
        "schema_version": "external_executor_capabilities.v1",
        "selected_executor": selected_executor or "UNSET",
        "network_available": real_executor,
        "github_access_available": real_executor,
        "dataset_download_supported": real_executor,
        "baseline_reimplementation_supported": real_executor,
        "static_review_supported": real_executor,
        "notes": (
            "Generated by ResearchOS T5-EXECUTOR-GATE. Real external executors "
            "are authorized for public resource acquisition and baseline "
            "reimplementation into resource/ within allowed paths."
            if real_executor
            else "Mock or unselected executor does not perform real acquisition."
        ),
    }
