from __future__ import annotations

from typing import Any


def default_resource_acquisition_policy() -> dict[str, Any]:
    """ResearchOS default authority for external executor resource preparation."""

    return {
        "mode": "github_and_reimplementation",
        "network_allowed": True,
        "github_access_allowed": True,
        "dataset_download_allowed": True,
        "baseline_reimplementation_allowed": True,
        "external_code_inspection_allowed": True,
        "authenticated_resources_allowed": False,
        "license_checks_required": True,
        "checksum_required": True,
        "citation_required": True,
        "allowed_domains": [
            "github.com",
            "raw.githubusercontent.com",
            "codeload.github.com",
            "objects.githubusercontent.com",
            "huggingface.co",
            "hf.co",
            "zenodo.org",
            "figshare.com",
            "kaggle.com",
            "openml.org",
            "archive.ics.uci.edu",
        ],
        "material_absence_policy": (
            "external_executor/expr may contain only README/checklist scaffolding; "
            "the external executor should acquire public resources or reimplement "
            "baselines under this policy when local materials are absent."
        ),
        "prohibited_actions": [
            "bypass_authentication_or_clickthrough_terms",
            "expose_secrets_or_private_paths",
            "execute_unreviewed_third_party_installers",
            "claim_official_status_for_executor_reimplementations",
        ],
    }


def default_executor_capabilities(selected_executor: str) -> dict[str, Any]:
    real_executor = selected_executor in {"codex_cli", "claude_code_window", "manual"}
    return {
        "schema_version": "external_executor_capabilities.v1",
        "selected_executor": selected_executor or "UNSET",
        "network_available": real_executor,
        "github_access_available": real_executor,
        "dataset_download_supported": real_executor,
        "baseline_reimplementation_supported": real_executor,
        "static_review_supported": real_executor,
        "notes": (
            "Generated by ResearchOS T5-EXECUTOR-GATE. Real external executors "
            "are authorized for public GitHub/resource acquisition and baseline "
            "reimplementation within allowed paths."
            if real_executor
            else "Mock or unselected executor does not perform real acquisition."
        ),
    }
