"""Read-only T4 input inspection and validated Pre-run directives."""

from __future__ import annotations

import json
from pathlib import Path
import re
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from ..runtime.bridge_catalog import load_bridge_catalog_summaries, validate_active_bridge_catalogs
from ..runtime.literature_contract import build_literature_manifest, iter_literature_note_cards
from .config import T4EvolutionSettings
from .models import T4RunConfig, TargetProfile
from .state import (
    T4ArtifactStore,
    build_t4_input_fingerprints,
    run_config_fingerprint,
    stable_fingerprint,
    t4_input_fingerprint,
)


class _Model(BaseModel):
    model_config = ConfigDict(extra="forbid")


class T4InputInspection(_Model):
    status: Literal["ready", "ready_with_warnings", "blocked"]
    input_fingerprint: str
    materials: dict[str, int | str]
    artifact_paths: dict[str, str]
    warnings: list[str] = Field(default_factory=list)
    blocking_issues: list[dict[str, str]] = Field(default_factory=list)


class T4PreRunDirective(_Model):
    action: Literal["start", "inspect", "pause"]
    mode: Literal["quick", "standard", "deep", "auto"] = "standard"
    allow_crossover: bool = True
    final_top_k: int = Field(default=3, ge=1, le=3)
    requested_rounds: int | None = Field(default=None, ge=0, le=3)
    raw_user_input: str = ""
    needs_confirmation: bool = False


_NOTE_ROOTS = (
    ("core_deep_cards", "literature/deep_read_notes", "core"),
    ("core_abstract_cards", "literature/shallow_read_notes", "core"),
    ("bridge_cards", "literature/bridge_notes", "bridge"),
)


def materialize_t4_cross_domain_catalog_context(workspace_dir: Path) -> dict[str, Any]:
    """Publish configured B1/B2/... tracks before a T4 run is fingerprinted.

    Cross-domain catalogs are retrieval context, not a deep-reading artifact.
    A normal T2 finalization already writes them, but old workspaces and some
    recovery paths can retain a confirmed ``bridge_domain_plan.json`` without
    the derived catalog.  Materializing that deterministic projection here
    keeps the user's named directions, retrieved records, and linked notes
    visible to T4 without inventing a note or requiring a bridge paper to have
    been deeply read.

    This helper is deliberately called only after a researcher chooses to
    start or re-profile T4, and before the run's input fingerprint is written.
    A failure is reported as contextual degradation rather than making an
    otherwise usable mainline T4 run impossible.
    """

    workspace = Path(workspace_dir)
    configured = _configured_bridge_domains(workspace)
    if not configured:
        return {
            "status": "not_configured",
            "configured_track_count": 0,
            "index_path": "literature/cross_domain_catalogs/index.json",
        }
    try:
        # A valid catalog has already been generated by T2 or an earlier
        # pre-run. Do not rewrite it just to inspect T4: historical
        # ``generated_at`` metadata would otherwise change the T4 fingerprint
        # on every resume even when no retrieval or reading input changed.
        valid, error = validate_active_bridge_catalogs(workspace)
        if valid:
            summaries = load_bridge_catalog_summaries(workspace, records_per_bridge=0)
            return {
                "status": "ready",
                "configured_track_count": len(configured),
                "index_path": "literature/cross_domain_catalogs/index.json",
                "bridge_count": len(summaries),
                "retrieved_record_count": sum(
                    int(item.get("record_count") or 0) for item in summaries if isinstance(item, dict)
                ),
            }
        # Import locally to keep the read-only inspection module free of a
        # module-level dependency on the T3 manifest writer.
        from ..runtime.t3_notes_manifest import refresh_bridge_catalogs

        result = refresh_bridge_catalogs(workspace)
        valid, error = validate_active_bridge_catalogs(workspace)
    except Exception as exc:  # pragma: no cover - defensive filesystem boundary
        return {
            "status": "degraded",
            "configured_track_count": len(configured),
            "index_path": "literature/cross_domain_catalogs/index.json",
            "warning": f"cross_domain_catalog_materialization_failed:{type(exc).__name__}",
        }
    if not valid:
        return {
            "status": "degraded",
            "configured_track_count": len(configured),
            "index_path": "literature/cross_domain_catalogs/index.json",
            "warning": str(error or "cross_domain_catalog_validation_failed"),
        }
    return {
        "status": "ready",
        "configured_track_count": len(configured),
        "index_path": str(result.get("index_path") or "literature/cross_domain_catalogs/index.json"),
        "bridge_count": int(result.get("bridge_count") or 0),
        "retrieved_record_count": int(result.get("retrieved_record_count") or 0),
    }


def inspect_t4_inputs(workspace_dir: Path) -> T4InputInspection:
    """Inspect actual files for the pre-run Gate without calling an LLM."""

    workspace = Path(workspace_dir)
    materials: dict[str, int | str] = {
        "core_deep_cards": 0,
        "core_abstract_cards": 0,
        "bridge_deep_cards": 0,
        "bridge_abstract_cards": 0,
        # Cross-domain retrieval is a separate contextual layer.  Keep these
        # counts distinct from Markdown reading notes so an empty
        # ``bridge_notes/`` directory is never presented as “no bridge
        # material”.
        "cross_domain_tracks": 0,
        "cross_domain_configured_tracks": 0,
        "cross_domain_retrieved_records": 0,
        "cross_domain_abstract_records": 0,
        "cross_domain_linked_reading_notes": 0,
        "synthesis": "available" if (workspace / "literature/synthesis.md").is_file() else "missing",
        "synthesis_workbench": "available" if (workspace / "literature/synthesis_workbench.json").is_file() else "missing",
        "domain_map": "available" if (workspace / "literature/domain_map.json").is_file() else "missing",
        "comparison_table": "available" if (workspace / "literature/comparison_table.csv").is_file() else "missing",
        "survey_insights": "available" if (workspace / "ideation/survey_insights.json").is_file() else "unavailable",
        "user_seed_ideas": _material_status(workspace / "user_seeds/seed_ideas.md"),
        "user_constraints": _material_status(workspace / "user_seeds/seed_constraints.md"),
    }
    build_literature_manifest(workspace, write=True)
    for card in iter_literature_note_cards(workspace, include_shallow=True):
        reading_level = _reading_level(workspace / card.rel_path)
        if card.root_type == "bridge_notes":
            materials["bridge_abstract_cards" if reading_level == "abstract" else "bridge_deep_cards"] += 1
        else:
            materials["core_abstract_cards" if card.root_type == "shallow_read_notes" or reading_level == "abstract" else "core_deep_cards"] += 1
    # Retrieved bridge records remain valuable as bounded inspiration even
    # before Reader creates a Markdown note.  Report them as a *catalog*, not
    # as “abstract reading notes”: the latter was misleading and made a
    # populated B1/B2/... track look empty whenever ``bridge_notes/`` did not
    # contain dedicated Markdown files.
    configured_bridge_domains = _configured_bridge_domains(workspace)
    materials["cross_domain_configured_tracks"] = len(configured_bridge_domains)
    bridge_catalogs = load_bridge_catalog_summaries(workspace, records_per_bridge=0)
    materials["cross_domain_tracks"] = len(bridge_catalogs)
    materials["cross_domain_retrieved_records"] = sum(
        int(item.get("record_count") or 0) for item in bridge_catalogs if isinstance(item, dict)
    )
    materials["cross_domain_abstract_records"] = sum(
        int(item.get("abstract_record_count") or 0) for item in bridge_catalogs if isinstance(item, dict)
    )
    materials["cross_domain_linked_reading_notes"] = sum(
        int(item.get("canonical_note_count") or 0) for item in bridge_catalogs if isinstance(item, dict)
    )

    required = {
        "project": "project.yaml",
        "synthesis": "literature/synthesis.md",
        "synthesis_workbench": "literature/synthesis_workbench.json",
        "domain_map": "literature/domain_map.json",
    }
    blocking = [
        {
            "artifact": path,
            "why": "T4 needs this upstream research artifact to build an Evidence Index and Opportunity Map.",
            "how_to_fix": "Resume the upstream stage that produces this artifact, then return to T4.",
        }
        for _label, path in required.items()
        if not (workspace / path).is_file()
    ]
    warnings: list[str] = []
    if not blocking and int(materials["core_deep_cards"]) == 0 and int(materials["core_abstract_cards"]) == 0:
        warnings.append("No readable Paper Cards were found. T4 can inspect synthesis artifacts, but evidence-linked candidates will be limited.")
    if int(materials["cross_domain_tracks"]):
        warnings.append(
            "Cross-domain 已配置 "
            f"{materials['cross_domain_tracks']} 条信息轨道，包含 "
            f"{materials['cross_domain_retrieved_records']} 条检索记录和 "
            f"{materials['cross_domain_linked_reading_notes']} 条已关联阅读笔记。"
            "这些资料可用于结构类比、边界发现和创新假设；不能单独证明机制或结果。"
        )
    elif configured_bridge_domains:
        warnings.append(
            "已确认 "
            f"{len(configured_bridge_domains)} 条 Cross-domain 候选方向，但尚未找到对应 catalog。"
            "开始 T4 时会先从已保存检索记录物化 B1/B2/... 信息轨道；这不要求 Bridge 深读笔记。"
        )
    elif int(materials["bridge_abstract_cards"]) and not int(materials["bridge_deep_cards"]):
        warnings.append("Bridge 阅读笔记目前仅为摘要级。它可以启发候选，但不能在未升级阅读前证明机制。")
    if materials["comparison_table"] == "missing":
        warnings.append("The comparison table is unavailable. T4 can continue, but baseline differentiation will be less specific.")
    status: Literal["ready", "ready_with_warnings", "blocked"]
    status = "blocked" if blocking else ("ready_with_warnings" if warnings else "ready")
    return T4InputInspection(
        status=status,
        input_fingerprint=t4_input_fingerprint(workspace),
        materials=materials,
        artifact_paths={**{key: value for key, value in required.items()}, "literature_manifest": "literature/literature_manifest.json"},
        warnings=warnings,
        blocking_issues=blocking,
    )


def default_run_config(
    settings: T4EvolutionSettings,
    directive: T4PreRunDirective | None = None,
    *,
    target_profile: TargetProfile | None = None,
) -> T4RunConfig:
    """Build a validated run config from settings and a parsed user directive."""

    directive = directive or T4PreRunDirective(action="start")
    # Standard is the first mode that gives a promising Seed enough room to
    # become a genuinely differentiated Candidate: P0 formation, then P1 and
    # P2 evolution.  These are exploration-cost defaults rather than quotas;
    # an unsupported route or deferred Child still leaves its valid Parents
    # visible.  Deep keeps one additional round for researchers who explicitly
    # choose the larger provider budget.
    mode_rounds = {"quick": 0, "standard": 2, "deep": 3, "auto": 2}
    rounds = directive.requested_rounds if directive.mode == "auto" and directive.requested_rounds is not None else mode_rounds[directive.mode]
    return T4RunConfig(
        mode=directive.mode,
        rounds=rounds,
        allow_crossover=directive.allow_crossover,
        final_top_k=directive.final_top_k,
        max_initial_population=settings.population.max_initial_population,
        active_population_size=settings.population.active_population_target,
        max_offspring_per_round=settings.offspring.max_total,
        max_crossover_children=settings.offspring.crossover_maximum if directive.allow_crossover else 0,
        bridge_policy=settings.bridge_policy_default,
        route_quotas={item.route: item.maximum for item in settings.route_quotas},
        target_profile=target_profile or TargetProfile(),
        raw_user_input=directive.raw_user_input,
    )


def has_current_t4_prerun_confirmation(workspace_dir: Path) -> bool:
    """Return whether a user-confirmed config still matches current T4 inputs."""

    workspace = Path(workspace_dir)
    catalog_context = materialize_t4_cross_domain_catalog_context(workspace)
    if catalog_context.get("status") == "degraded":
        return False
    store = T4ArtifactStore(workspace)
    # Migrate only representations that do not add scientific input before
    # judging a historical receipt. Real catalog records, note changes and
    # synthesis changes remain confirmation-invalidating evidence changes.
    store.migrate_t4_input_fingerprint_schema()
    inspection = inspect_t4_inputs(workspace)
    if inspection.status == "blocked":
        return False
    current_fingerprints = build_t4_input_fingerprints(workspace)
    current_fingerprint = stable_fingerprint(current_fingerprints)
    receipt_path = workspace / "ideation" / "evolution" / "pre_run_confirmation.json"
    try:
        receipt = json.loads(receipt_path.read_text(encoding="utf-8"))
        config = store.read_run_config()
    except (OSError, ValueError, json.JSONDecodeError):
        return False
    return bool(
        isinstance(receipt, dict)
        and receipt.get("semantics") == "t4_pre_run_confirmation"
        and inspection.input_fingerprint == current_fingerprint
        and receipt.get("input_fingerprint") == current_fingerprint
        and receipt.get("run_config_fingerprint") == run_config_fingerprint(config)
        and config.target_profile.confirmed_by_user
        and _t4_confirmation_fingerprint_map_matches(receipt, current_fingerprints)
    )


def _t4_confirmation_fingerprint_map_matches(
    receipt: dict[str, Any],
    current_fingerprints: dict[str, dict[str, Any]],
) -> bool:
    """Validate component-level T4 inputs when the confirmation records them.

    Older receipts contain only an aggregate fingerprint and are still checked
    through that aggregate.  New receipts additionally preserve the component
    map, which makes a stale scientific input diagnosable without treating a
    PDF availability update as a new paper-note corpus.
    """

    recorded = receipt.get("input_fingerprints")
    if recorded is None:
        return True
    if not isinstance(recorded, dict):
        return False
    normalized = dict(recorded)
    # ``core_shallow_read_notes`` was the previous spelling for the canonical
    # ``literature/shallow_read_notes`` root.  It is safe to normalize only
    # when the new key is absent: the value remains byte-for-byte subject to
    # the comparison below, so a changed shallow note cannot pass through this
    # compatibility branch.
    old_shallow = normalized.pop("core_shallow_read_notes", None)
    if old_shallow is not None and "core_abstract_notes" not in normalized:
        normalized["core_abstract_notes"] = old_shallow
    return normalized == current_fingerprints


def parse_t4_prerun_intent(text: str) -> T4PreRunDirective:
    """Deterministic validation fallback for a future LLM semantic parser.

    The runtime will first ask an LLM directive parser when configured. This
    conservative parser recognizes unambiguous menu language and makes all
    budget-changing requests explicit rather than guessing researcher intent.
    """

    raw = " ".join(str(text or "").strip().split())
    lowered = raw.casefold()
    if not raw:
        return T4PreRunDirective(action="start", raw_user_input=raw)
    if any(token in lowered for token in ("pause", "暂停")):
        return T4PreRunDirective(action="pause", raw_user_input=raw)
    if any(token in lowered for token in ("inspect", "查看材料", "查看输入", "证据覆盖")):
        return T4PreRunDirective(action="inspect", raw_user_input=raw)
    mode = "standard"
    if any(token in lowered for token in ("quick", "快速", "formation only")):
        mode = "quick"
    elif any(token in lowered for token in ("deep", "两轮", "2轮")):
        mode = "deep"
    elif "auto" in lowered or "自动" in lowered:
        mode = "auto"
    allow_crossover = not any(
        token in lowered
        for token in ("no crossover", "without crossover", "不要 crossover", "不使用 crossover", "禁用 crossover")
    )
    top_match = re.search(r"(?:top|show|展示|候选)\s*([1-3])\s*(?:个|candidates?)", lowered)
    top_k = int(top_match.group(1)) if top_match else 3
    round_match = re.search(r"(?:rounds?|轮)\s*([0-3])", lowered)
    requested_rounds = int(round_match.group(1)) if round_match and mode == "auto" else None
    needs_confirmation = not allow_crossover or (requested_rounds is not None and requested_rounds >= 3)
    return T4PreRunDirective(
        action="start",
        mode=mode,
        allow_crossover=allow_crossover,
        final_top_k=top_k,
        requested_rounds=requested_rounds,
        raw_user_input=raw,
        needs_confirmation=needs_confirmation,
    )


def _paper_note_paths(root: Path) -> list[Path]:
    if not root.is_dir():
        return []
    return [
        path for path in root.rglob("*.md")
        if path.is_file() and not path.name.startswith("_") and path.name.lower() not in {"readme.md"}
    ]


def _configured_bridge_domains(workspace_dir: Path) -> list[dict[str, Any]]:
    """Read named bridge tracks without mistaking them for retrieved evidence."""

    path = Path(workspace_dir) / "literature" / "bridge_domain_plan.json"
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError, json.JSONDecodeError):
        return []
    raw = payload.get("bridge_domains") if isinstance(payload, dict) else []
    return [
        item
        for item in raw
        if isinstance(item, dict) and str(item.get("bridge_id") or "").strip()
    ] if isinstance(raw, list) else []


def _reading_level(path: Path) -> Literal["deep", "abstract"]:
    path_text = path.as_posix().casefold()
    if "abstract" in path_text or "shallow" in path_text:
        return "abstract"
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:8000].casefold()
    except OSError:
        return "deep"
    return "abstract" if "[abstract" in head or "abstract-only" in head else "deep"


def _material_status(path: Path) -> str:
    if not path.is_file() or path.stat().st_size == 0:
        return "unavailable"
    try:
        text = path.read_text(encoding="utf-8", errors="replace").strip()
    except OSError:
        return "unavailable"
    return "loaded" if text and text not in {"# Seed ideas", "# Seed constraints"} else "unavailable"
