"""Coverage for complete, consistent generated workspace directory guides."""

from __future__ import annotations

from researchos.runtime.workspace import DIRECTORY_GUIDE_CONTRACT_VERSION, initialize_workspace


def test_every_generated_directory_guide_explains_ownership_and_recovery(tmp_path) -> None:
    """Guide navigation must remain useful across every standard artifact directory."""

    initialize_workspace(tmp_path, project_id="guide-contract")

    required_markers = (
        "# Workspace Directory Guide",
        "| 目录用途 |",
        "| 生成阶段/来源 |",
        "| 下游使用方 |",
        "| 人工可编辑范围 |",
        "| Agent 可写范围 |",
        "| 不应放入 |",
        "| 校验/恢复规则 |",
        "## Key Files",
        "Generated by ResearchOS workspace initialization.",
        f"Guide contract: {DIRECTORY_GUIDE_CONTRACT_VERSION}.",
    )
    missing: dict[str, list[str]] = {}
    for path in sorted(tmp_path.rglob("_DIR_GUIDE.md")):
        text = path.read_text(encoding="utf-8")
        absent = [marker for marker in required_markers if marker not in text]
        if absent:
            missing[path.relative_to(tmp_path).as_posix()] = absent

    assert not missing, f"Incomplete generated directory guides: {missing}"
